### PR TITLE
Fix import swig package in site-packages using swig >= 3.0.9

### PR DESCRIPTION
**Pull request by mastersin**
Check `__name__.rpartition('.')` return for separator and return last
part of string if it doesn't same as expected.

See issue #769.

### CODE REVIEW

**Comment by ojwb** [comment]
This breaks Python 2.4 (syntax error from the inline `if`: https://travis-ci.org/swig/swig/jobs/280310758).  While older Python isn't very interesting now, it'd be better to just use a multi-line if and keep this working in case anyone cares, at least if this change is going to be backported to 3.0.x.

Python 3 also failed on OS X, but due to travis flaky infrastructure reasons - I've restarted so we can see if there are any actual issues there (it passed on Linux, so likely not).

@wsfulton In #769 you concluded:
> Okay, let's not try support the 'new' requirement. If anything, let's just make the documentation clearer in this respect.

What are your thoughts on this patch?  It seems clean and very unlikely to break anything, but we've had bad experiences with changing this import logic and `%pythonimport` now provides an override.

**Comment by mastersin** [comment]
2017-09-27 22:45 GMT+03:00 Olly Betts <notifications@github.com>:

> This breaks Python 2.4 (syntax error from the inline if:
> https://travis-ci.org/swig/swig/jobs/280310758). While older Python isn't
> very interesting now, it'd be better to just use a multi-line if and keep
> this working in case anyone cares, at least if this change is going to be
> backported to 3.0.x.
>
This is looks like a strange bug for python-2.4 due there are a check for
python version in original code - "if _swig_python_version_info >= (2, 7,
0):":

diff --git a/swig/Source/Modules/python.cxx b/swig/Source/Modules/python.cxx
index a6801fc..7aa08ba 100644
--- a/swig/Source/Modules/python.cxx
+++ b/swig/Source/Modules/python.cxx
@@ -846,7 +846,8 @@ public:
       Printv(default_import_code, "if _swig_python_version_info >= (2, 7,
0):\n", NULL);
       Printv(default_import_code, tab4, "def swig_import_helper():\n",
NULL);
       Printv(default_import_code, tab8, "import importlib\n", NULL);
-      Printv(default_import_code, tab8, "pkg =
__name__.rpartition('.')[0]\n", NULL);
+      Printv(default_import_code, tab8, "pkg_parts =
__name__.rpartition('.')\n", NULL);
+      Printv(default_import_code, tab8, "pkg = pkg_parts[0] if
pkg_parts[1] == '.' else pkg_parts[2]\n", NULL);
       Printf(default_import_code, tab8 "mname = '.'.join((pkg,
'%s')).lstrip('.')\n", module);
       Printv(default_import_code, tab8, "try:\n", NULL);
       Printv(default_import_code, tab8, tab4, "return
importlib.import_module(mname)\n", NULL);


> Python 3 also failed on OS X, but due to travis flaky infrastructure
> reasons - I've restarted so we can see if there are any actual issues there
> (it passed on Linux, so likely not).
>
> @wsfulton <https://github.com/wsfulton> In #769
> <https://github.com/swig/swig/issues/769> you concluded:
>
> Okay, let's not try support the 'new' requirement. If anything, let's just
> make the documentation clearer in this respect.
>
> What are your thoughts on this patch? It seems clean and very unlikely to
> break anything, but we've had bad experiences with changing this import
> logic and %pythonimport now provides an override.
>

-- 
Sin (Sinelnikov Evgeny)

**Comment by ojwb** [comment]
> This is looks like a strange bug for python-2.4 due there are a check for python version in original code - "if _swig_python_version_info >= (2, 7, 0):":

It's a syntax error - Python presumably needs to be able to parse the code inside that branch even if though it's not executed.  For example, with Python 3.5 you get a syntax error for a non-executed `print` without parentheses:

```
$ python3.5
Python 3.5.4 (default, Sep  5 2017, 18:32:10) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> if False:
...     print "foo"
  File "<stdin>", line 2
    print "foo"
              ^
SyntaxError: Missing parentheses in call to 'print'
```

And it's easily worked around - just use a multi-line `if`.

**Comment by wsfulton** [comment]
I've merged in #1282 which seems to fix #769. @mastersin, can you please close this issue when confirmed that it works for you? Thanks.

**Comment by wsfulton** [comment]
No response, assuming fixed.

**Comment by neinhus** [comment]
From my point of view it could lead to problems to do this:
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_FSNativeTauIO')
Reason: the import error may be also that a depending shared library is not found. The error message thrown is "No module named _<name>"  but in my case the true error message was:  
ImportError: lib<somename>.so.<nr>: cannot open shared object file.
This can be difficult to debug without looking into the wrapper code.

**Comment by wsfulton** [comment]
@neinhus, the various issues linked to here have been fixed for swig-4.0.0. There is no try except block anymore for the module import.

**Pull request closed without merging**
