### PR TITLE
Python: Fix property access with director

### PR DESCRIPTION
**Pull request by diorcety**
When adding a property in a class extending a directory class, we can't set/read property correctly.
Here the fix, and the test

### CODE REVIEW

**Comment by wsfulton** [comment]
@diorcety Looks like this change has broken use of swig with -classic as mentioned on the swig-devel mailing list. It is pretty urgent to fix this, are you around to take a look? Probably the test-suite goes wrong when run with -classic, but I am not able to check right now.

**Comment by diorcety** [comment]
i will take a look this evening

**Comment by diorcety** [comment]
Ok maybe we have to add a switch in the case of modern or !classic . __setattr__ is maybe not defined in the old style class or something like that

**Comment by wsfulton** [comment]
The python_nondynamic testcase reproduces the problem:

```
checking python testcase python_nondynamic (with run test)
Traceback (most recent call last):
  File "python_nondynamic_runme.py", line 46, in <module>
    cc.d = 3
  File "/home/william/swig/github/swig/Examples/test-suite/python/python_nondynamic.py", line 100, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, C, name, value)
  File "/home/william/swig/github/swig/Examples/test-suite/python/python_nondynamic.py", line 51, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/william/swig/github/swig/Examples/test-suite/python/python_nondynamic.py", line 45, in _swig_setattr_nondynamic
    object.__setattr__(self, name, value)
TypeError: can't apply this __setattr__ to instance object
make[1]: *** [python_nondynamic.cpptest] Error 1
```

The classic and modern flags in python.cxx are set when -classic and -modern are passed on the command line, so you can use those and I suggest generating the old code when -classic is set. The generated .py file also contains a _newclass variable which looks like it could be used.

**Comment by wsfulton** [comment]
Fix committed. With new style classes __setattr__ is used and with old style classes __dict__ is used (like it used to be). Amazingly the director_property testcase in this patch now works with old style classes and new style classes :)

**Pull request merged**
