### PR TITLE
Fix class name for nested classes

### PR DESCRIPTION
**Pull request by IsaacPascual**
The feature %interface_impl from swiginterface.i differ on generated function
name from JNI wrapper class when using nested classes without flatnested.

### CODE REVIEW

**Comment by IsaacPascual** [comment]
Sorry for brach name I dont see how to change it.

**Comment by wsfulton** [comment]
Can you give a full example of what this fixes please? Also a new testcase would be much appreciated, perhaps copy and modify one of the Examples/test-suite/multiple_inheritance* testcases.

**Comment by IsaacPascual** [comment]
Well it fail in a big-complex project. Im trying to reproduce in a small project but is more difficult than I think.

**Comment by IsaacPascual** [comment]
My problem is that code on ModuleJNI.java:
`
  public final static native long pack_B_I_GetInterfaceCPtr(long jarg1);
`
And on class B ( nested of A ) has not equal name for functions:
`
public long I_GetInterfaceCPtr() {
    return pack.ModuleJNI.pack_A_B_I_GetInterfaceCPtr(swigCPtr);
}
`

All the calls to Swig_name_member go with getClassPrefix() I try and it solve my problem.

**Comment by IsaacPascual** [comment]
This is a basic case:
[example.tar.gz](https://github.com/swig/swig/files/3339053/example.tar.gz)

Module.h
```cpp
class Interface
{
};

class Class
{
public:
	class Nested : public Interface
	{
	};

};
```

Module.i
```
%module Module

%include <swiginterface.i>

%interface_impl(Interface);

%include "Module.h"
```

Makefile
```makefile
all:
	@mkdir -p pack
	swig -c++ -java -package pack -outdir pack/ Module.i

test:
	@grep -r --color "Nested_Interface_GetInterfaceCPtr" pack/

clean:
	rm -rf pack Module_wrap.cxx
```

**Comment by IsaacPascual** [comment]
The problem is that the method on `pack/ModuleJNI.java`:
```java
public final static native long Nested_Interface_GetInterfaceCPtr(long jarg1);
```
and the use generated on `pack/Class.java`:
```java
return ModuleJNI.Class_Nested_Interface_GetInterfaceCPtr(swigCPtr);
```
dont have the same name!

You can see the problem with:
`make; make test`

**Comment by IsaacPascual** [comment]
I try the test on `master` and fail but not in `patch-1`

**Comment by IsaacPascual** [comment]
Ups some problem with csharp... but I only want this test for java... Some help please my first time writing tests for swig...

**Comment by IsaacPascual** [comment]
Well! I fix it for `csharp` and implement a test case. It gonna be merged? or there is something more to do??

**Comment by wsfulton** [comment]
Looks good to me, thanks for adding in the test-case. I fixed a minor C# compiler warning, see 20d96531e3a5fef442a13dee55020d53a452d7f8.

**Pull request merged**
