### PR TITLE
[R] Add argc and argv multi-argument typemap.

### PR DESCRIPTION
**Pull request by erezgeva**
Need a fix on rtypecheck.

Currently under Debug.

### CODE REVIEW

**Comment by ojwb** [comment]
A couple of notes for when you get this working:

I spotted a bug in the octave `argcargv.i` implementation which needs to copy the string data but wasn't doing so and as a result every entry in the argv passed to C/C++ was actually the final string from the octave array.  The testcase was only testing the value of a last entry so missed this bug.  I've modified all the existing `argcargvtest_runme.*` to test the first entry too - it would be good to copy that extra coverage over for R.

Some of the implementations accepted an empty target language array whereas others explicitly rejected it.  It seems valid for the array to be empty (resulting in `argc == 0` and `argv[0] == NULL` on the C/C++ side) so I've fixed the target languages which didn't allow this _(*)_, and added test coverage for this for all languages.  It ought to work and have test coverage for R too.

---
_(*) Looking at 4ba7e68c286e38b0ae8a4db5028e7ec4b5172538 I see I didn't finish this for D, and the testcase change for it is commented out - I'll push a fix for that soon._

**Comment by erezgeva** [comment]
> A couple of notes for when you get this working:
> 
> I spotted a bug in the octave `argcargv.i` implementation which needs to copy the string data but wasn't doing so and as a result every entry in the argv passed to C/C++ was actually the final string from the octave array. The testcase was only testing the value of a last entry so missed this bug. I've modified all the existing `argcargvtest_runme.*` to test the first entry too - it would be good to copy that extra coverage over for R.
> 
> Some of the implementations accepted an empty target language array whereas others explicitly rejected it. It seems valid for the array to be empty (resulting in `argc == 0` and `argv[0] == NULL` on the C/C++ side) so I've fixed the target languages which didn't allow this _(*)_, and added test coverage for this for all languages. It ought to work and have test coverage for R too.
> 
> _(*) Looking at [4ba7e68](https://github.com/swig/swig/commit/4ba7e68c286e38b0ae8a4db5028e7ec4b5172538) I see I didn't finish this for D, and the testcase change for it is commented out - I'll push a fix for that soon._

@ojwb 
Thanks for catching these bugs and adding more testings :-)
As for R, it have an issue with the `rtypecheck` typemap.
It does not use it properly, as a result the dispatch of `initializeApp()` always fail.

I though fixing the using of `rtypecheck` typemap in R.
Once it is works properly, I will update the R `runme` to follow other `argcargvtest_runme` tests.
And ensure R `argcargv.i` works the same as other languages.

**Comment by erezgeva** [comment]
I think I found the missing `rtypecheck` in r`.cxx`.
Once the test pass, I will create proper patches.

R also use `NULL` for empty array like D lang.
Probably this idea is more spread ...

**Comment by erezgeva** [comment]
@wsfulton
I saw this message in ``Source/Modules/r.cxx":
`Below should be migrated into rtypecheck typemaps`

I add `%typemap(rtypecheck)`, so perhaps we now can?

**Comment by erezgeva** [comment]
@ojwb

Ready for merge.

OCaml does not have ARGC ARGV typemap,
There is probably a good reason to remove this language.
There is no way to pass string array from OCaml to Swig wrapper.

**Comment by ojwb** [comment]
Gah, I'm in the middle of merging this and you've just updated it.

If you're still working on a branch, please don't say it's "Ready to merge".

**Comment by ojwb** [comment]
Rebasing at this point is actively unhelpful - please stop changing things here unless there's actually something which should hard block the merge.  Improvements and minor fixes we can apply fixes afterwards.

**Comment by erezgeva** [comment]
> Rebasing at this point is actively unhelpful - please stop changing things here unless there's actually something which should hard block the merge. Improvements and minor fixes we can apply fixes afterwards.

OK, I stop.
I think it is in a good shape.

**Comment by ojwb** [comment]
OK, merged.

I did a `git merge --squash` of the PR branch on top of my merge and included that in the push, so I think all your changes are included, but it needed significant manual resolving of conflicts so probably worth you checking.

I noticed while merging that we weren't `NULL` terminating `argv` in the empty array case for R (which your refactor also fixed) and for C# at all, so I've fixed those and added test coverage to check we get this right for all the target languages in 8a73e25fe2a1bd1bbffb052d47891238287aea7d.

**Comment by erezgeva** [comment]
> OK, merged.
> 
> I did a `git merge --squash` of the PR branch on top of my merge and included that in the push, so I think all your changes are included, but it needed significant manual resolving of conflicts so probably worth you checking.
> 
> I noticed while merging that we weren't `NULL` terminating `argv` in the empty array case for R (which your refactor also fixed) and for C# at all, so I've fixed those and added test coverage to check we get this right for all the target languages in [8a73e25](https://github.com/swig/swig/commit/8a73e25fe2a1bd1bbffb052d47891238287aea7d).

I compared `Lib/r/argcargv.i`. 
The only different is I removed the `noblock` attribute from `%typemap(in)`, as C forbids defining variables in a middle of a block. (We run tests in C++ only).

As for `NULL` terminating, I probably missed it. Nice catch!

Thanks for merging, enhancing, finding bugs and your time.
Erez

**Comment by ojwb** [comment]
> The only different is I removed the `noblock` attribute from `%typemap(in)`, as C forbids defining variables in a middle of a block. (We run tests in C++ only).

Oops, pushed a fix for that.

It would probably also fail for C++ if the typemap applied twice to the same function due to declaring a variable which is already declared in that scope.

**Pull request closed without merging**
