### PR TITLE
Fix for missing smart pointer handling in Java director extra methods implementation

### PR DESCRIPTION
**Pull request by asibross**
Missing smart pointer handling in Java director extra methods implementation.

### CODE REVIEW

**Comment by wsfulton** [comment]
I commented on this patch in issue #417 but I should probably have done it here, so please look look at today's comments there.

**Comment by wsfulton** [comment]
Please rebase this patch and change the commit message such that the first line is swapped with the body of the commit message. When reading the one line logs, the text should make sense, currently you have 'Fixing issue #370' which is pretty useless without having to go and find the issue in Github.

**Comment by asibross** [comment]
I have performed the rebase and changed the commit message.

As for lack of support for shared_ptr and director, the documentation in http://swig.org/Doc3.0/SWIGDocumentation.html states that:
"There is currently no support for %shared_ptr and the director feature."

As for the tests, I am having problem building swig and the examples in my Windows box so I omitted them out.

**Comment by wsfulton** [comment]
Please post something about test code that requires this fix in the ticket and I'll attempt to create a test case and before merging in your patch.

**Comment by wsfulton** [comment]
Ping @asibross ... please provide further details to recreate the bug.

**Comment by wsfulton** [comment]
@asibross, could you please provide more details for what this fixes. Thanks.

**Comment by wsfulton** [comment]
I added a runtime test in a4d01cddebf8568116bad93a2ffb783cd925c783 to show it is fixed.

**Pull request merged**
