### PR TITLE
[python] prevent _swigconstant boilerplate for non-class types

### PR DESCRIPTION
**Pull request by ptomulik**
In response to  #344, #563.

This patch reverts the old way of generating code for ``%constant``s if the constant's type is not a class. It shall reduce the code-bloat for primitive constants (``int``, ``enum`` and so on). I hope it fixes [regression](https://github.com/swig/swig/issues/563#issuecomment-193542011) mentioned in #563.

Note, that cases such as:

```c++
struct T { /* ... */  };
T v1, v2, v3, v4, v5;
//...
%constant T& t1 = &v1;
%constant T const& t2 = &v2;
%constant T* t3 = &v3;
%constant T const* t4 = &v4;
%constant T const* const& t5 = &v5;
```
will be handled as class objects (i.e. ``_swigconstant`` will be generated) -- pointers, references, qualifiers and template arguments get stripped before determining whether the constant's type is a class or not.

### CODE REVIEW

**Comment by wsfulton** [comment]
The unnecessary _swigconstant helpers are nearly all gone. I compared the test-suite to just before #250 was pulled and the li_std_stream.i and li_std_wstream.i testcases are the only ones generating _swigconstant helpers compared to before #250. These are for std::endl, std::ends, std::flush in Lib/std/std_iostream.i. I suspect SwigType_isclass() is failing in some way, but is probably a separate bug.

**Comment by wsfulton** [comment]
Merged in c1d200ba7da53c50dbb682adb2319994e27500c9

**Comment by ptomulik** [comment]
Perhaps std:endl and siblings are somehow treated as constants by swig (in C++ they're global variables AFAIR). Then they're constant objects of class type, so they will generate the _swigconstant helpers, and it should be expected I think.

**Comment by ptomulik** [comment]
I was wrong, std::endl is a function (pointer to a function?).

**Comment by ptomulik** [comment]
It may be ``SwigType_base`` (or rather the fact that I have used it). I suspect that for function and function pointer types it returns the return type of function, which in our case is a class type (std::ostream for std::end(...)).

**Comment by ojwb** [comment]
I've tested this with [xapian](https://xapian.org/)'s bindings, and all the `_swigconstant` functions are all gone again there.  Thanks for the fix.

**Comment by ptomulik** [comment]
further fixes to ``%constant``'s are included in #641. You can test it as well.

**Comment by ojwb** [comment]
The further fixes sound good, but I don't have any function pointer constants to check the wrapping of.

**Pull request closed without merging**
