### PR TITLE
Matlab branch updated for Swig 4.0.0

### PR DESCRIPTION
**Pull request by Alzathar**
Work done:
 - merge the `jaeandersson/swig:matlab` branch (commit cd3f6c5 which is 12 commits ahead of the `swig/swig:matlab` branch)
 - merge the `swig/swig:master branch` (commit b04cc850a)
 - corrections of few conflicts
 - integration of Matlab examples when possible
 - compiled on macOS 10.12.6 with Xcode 9.2 and Matlab R2014a (64-bit)
 - tests ran with the command `make check-matlab-examples` and `make check-matlab-test-suite`

The output of the first command is above
```
$ make check-matlab-examples
checking Examples/matlab/constants
checking Examples/matlab/contract
checking Examples/matlab/enum
checking Examples/matlab/funcptr
checking Examples/matlab/funcptr2
checking Examples/matlab/reference
checking Examples/matlab/simple
checking Examples/matlab/template
checking Examples/matlab/variables
```

The output of the second command is in the attached file [check-matlab-test-suite.log](https://github.com/swig/swig/files/3113126/check-matlab-test-suite.log). To summarize this log:
 - no runme test present: 450 tests
 - passed: 68 tests
 - failed: 16 tests
 - compilation error: 7 tests

Regarding the compilation error, several tests did not compile because the header `boost/shared_ptr.hpp` was not found (even if the option `--with-boost=no` was added to configure the compilation of swig). FYI, the problem is the same for the python test suite. Maybe an issue should be reported for this.

I will continue to update this PR with the implementation of more tests and given recommandations.

### CODE REVIEW

**Comment by wsfulton** [comment]
Hi @Alzathar. This pull request contains many changes in files that are not related to Matlab. This points to something going horribly wrong in your merge. I expect to only see changes in files related to Matlab.

Installing boost is a prerequisite for a successful test-suite run in all languages, so you do need to install boost and test with it.

Merging Matlab into master requires co-ordination with the original authors, in particular I'd like the pull request to be sanctioned by @jaeandersson. The pull request also needs to meet the 'experimental status', see #1437. As mentioned there, the Matlab module is Octave/Matlab bilingual. The pull request will need to include Travis tests demonstrating this.

**Comment by Alzathar** [comment]
Hi @wsfulton. This PR proposes to update the `swig:matlab` by syncing it against the `swig:master` branch. I do not propose to merge the `swig:matlab` branch into the `swig:master` branch. Because the latest commit in the`matlab` branch was between the 3.0.11 and 3.0.12 releases, lost of commits are only related to the improvement of Swig and the next 4.0.0 release. If I propose a PR to include the Matlab language into the `swig:master` branch without using the `swig:matlab` branch, the result might be different. Do you prefer the second one?

>  Installing boost is a prerequisite for a successful test-suite run in all languages, so you do need to install boost and test with it.

Good to know

> Merging Matlab into master requires co-ordination with the original authors, in particular I'd like the pull request to be sanctioned by @jaeandersson. 

I totally agree. But this PR is only to sync the `swig:master` branch to continue the improvement of the Matlab language support. I decided to propose this PR in the main repository of Swig instead of the one of @jaeandersson because this one was not updated since one year (no merge against the 3.0.12 release or newer commit).

> The pull request also needs to meet the 'experimental status', see #1437. 

I think I did this correctly (see the commit [2d8a141](https://github.com/Alzathar/swig/commit/2d8a1410348b5ef6e678a0050501af70882cc5dc)).

> As mentioned there, the Matlab module is Octave/Matlab bilingual. The pull request will need to include Travis tests demonstrating this.

I can update the Travis script to enable the Matlab and Octave language.

**Comment by jaeandersson** [comment]
@alzathar and @wsfulton 
Great to see this effort on getting the MATLAB/Octave module merged and more properly tested. I am feeling a bit bad for not being able to take the time to work on this myself and I'm more than happy to pass on the baton to someone else to get the work finished. This module could be very useful to a lot of people so it's really a shame to leave it unmerged.

If @wsfulton's concerns regarding changes unrelated to Matlab are properly addressed, I there are no objections from my end.

@jgillis might have something to add.

**Comment by wsfulton** [comment]
@Alzathar sorry, I completely missed exactly what was being merged and where. I get it now. I think jaeandersson/swig:matlab should be considered the reference branch. If there is something in swig/swig:matlab, then that should be merged into jaeandersson/swig:matlab as a first preliminary step to create a new reference branch. 

In order to merge into swig/swig:master, a maintainer is needed. @Alzathar if you are prepared to take that on and see this work through (we'd lover that!), then please make that clear and I suggest you prepare this in your own github repo. From there propose a pull request for merging into swig/swig:master. The patch will need to meet the experimental language minimum requirements, please see http://swig.org/Doc4.0/Extending.html, in particular http://swig.org/Doc4.0/Extending.html#Extending_language_status detailing the minimum requirements. There is more to do than https://github.com/Alzathar/swig/commit/2d8a1410348b5ef6e678a0050501af70882cc5dc :(. Getting Travis build for Octave and Matlab for the new branch would be an important step in that journey.

**Comment by jaeandersson** [comment]
@wsfulton @Alzathar I'm a bit confused.. are you waiting for me to approve this PR?

**Comment by jaeandersson** [comment]
Or should I pull these changes into jaeandersson/swig:matlab?

**Comment by Alzathar** [comment]
@wsfulton Can you explain if you want @jaeandersson to approve this PR?

**Pull request closed without merging**
