### PR TITLE
Python: Add option to suppress generation of flattened static class methods

### PR DESCRIPTION
**Pull request by jim-easterbrook**
Following a recent discussion on the swig-user mailing list this PR adds an option to suppress the generation of "flattened" static class methods.
https://sourceforge.net/p/swig/mailman/swig-user/thread/CANGqftAP39z0ORLgzJgY7DoTi%2Bj7J%2BqeRTppgnoP8p_Hqya0kA%40mail.gmail.com/#msg37370221

I'd welcome suggestions for a better name for the option!

### CODE REVIEW

**Review by casperdcl — APPROVED** [review]

**Comment by wsfulton** [comment]
To fit in with the Zen of python _There should be one-- and preferably only one --obvious way to do it_, I propose we remove the flattened methods by default and add in an option to add them back in for the not-so-Zen users :). I suggest `-flatmembermethods` for the option name.

I was also considering static member variables. I was thinking of also dropping the flattened static member variables (wrapped into cvar). It would mean they could only be accessed via an instance though. I don't see this being always possible as it is not always possible to instantiate all classes (such as when the constructors are not public) and instantiating one has side effects and may be slow. With `-builtin`, though, it is possible to read and write these static member variables without instantiation using syntax like Spam.bar as well as cvar.Spam_bar in addition to instantiating like Spam().bar. The `-builtin` implementation is via a metaclass, which we could port to non-builtin proxy classes. If that was implemented we could also remove the flattened ones in cvar. Probably a separate patch for this though.

**Comment by jim-easterbrook** [comment]
My concern was not to break existing uses, hence the default is things stay as they are.

I've not looked at static member variables - I don't think anything I've used SWIG for has them.

**Comment by wsfulton** [comment]
We're doing a major release next so this is the time where some non-backwards compatible changes  can be accepted.

**Comment by ojwb** [comment]
#2137 takes the alternative approach William proposes here, so closing this in favour of that.

**Pull request closed without merging**
