### PR TITLE
Miscellaneous CI improvements

### PR DESCRIPTION
**Pull request by vadz**
The goal is to bring the GitHub Actions to parity with the old Travis CI.

### CODE REVIEW

**Comment by vadz** [comment]
Assuming the last build passes, this should be ready to be merged, even if more improvements remain possible, of course.

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
a number of jobs still queued on Appveyor. https://ci.appveyor.com/project/swig/swig/history. Those should probably be cancelled except the last one. (and use `[appveyor skip']' in future)

**Comment by vadz** [comment]
> a number of jobs still queued on Appveyor. https://ci.appveyor.com/project/swig/swig/history. Those should probably be cancelled

Unfortunately I don't have permissions to cancel these builds on AppVeyor, so the best (and only) thing I can do is tol make a PR to cancel the old builds of PRs on AppVeyor if a new PR version is available in the future to avoid this happening again. In any case they should pass because nothing here really affects AppVeyor builds at all (so I'll also add `skip_commits` to `appveyor.yml`...).

> (and use `[appveyor skip']' in future)

Personally I dislike littering the Git history forever with directives for the CI systems. At least `[skip ci]` on its own has some semantic meaning, but I don't like using directives for AppVeyor (or anything else) specifically at all.

**Comment by vadz** [comment]
Merging this did cancel the outstanding AppVeyor builds for this PR, so at least this problem was easy to fix.

**Pull request merged**
