### PR TITLE
#733 - wrong "override" calculation in import mode

### PR DESCRIPTION
**Pull request by wkalinin**
"override" calculation in allocate.cxx should take into account interfaces.
"direct_base" attribute has no other use now, so it may be removed completely (it had some intended usage, but I can't remember what exactly)

### CODE REVIEW

**Comment by wsfulton** [comment]
Could you please put in a testcase for this?

**Comment by wkalinin** [comment]
Looks like there are zero tests of import mode in the test suite.

**Comment by wsfulton** [comment]
I can see these:
```
~/swig/github/swig/Examples/test-suite (master=)$ grep "%import" -l *
clientdata_prop_b.i
go_subdir_import_a.i
import_nomodule.i
imports_a.i
imports_b.i
import_stl_b.i
mod_b.i
multi_import_a.i
packageoption_c.i
template_typedef_import.i
```
Note that most of these are run using ```make xx.multicpptest``` instead of ```make xx.cpptest```. Maybe you mean some other sort of import?

**Comment by wkalinin** [comment]
Oh, indeed there are. Somehow my search for "#import" gave me no results, probably I misspelled it.
As I understand, test case should be a C# runtime one? I'll try to make one taking some other test as a model, but it will probably take some iterations, because I was unable to set up C# test suite working

**Comment by wsfulton** [comment]
C# should work out the box if you install the appropriate packages:
```
sudo apt-get install mono-devel #ubuntu/debian
zypper install mono-core #suse
sudo dnf install mono-core #fedora
```
SWIG has ```%import``` and C# does not have a ```#import```.

Do you have any emails/other info on the problem, I presume it is is related to the new %interface support we added recently.

**Comment by wkalinin** [comment]
I referenced the issue in the commit comment, it is: https://github.com/swig/swig/issues/733

**Pull request merged**
