### PR TITLE
[OCaml] Update OCaml for out-of-source builds

### PR DESCRIPTION
**Pull request by ZackerySpytz**
This is one of the steps needed to fix the OCaml test suite.

In addition, disable the creation of toplevels by default in the OCaml
examples (toplevels are currently broken).

### CODE REVIEW

**Comment by wsfulton** [comment]
A couple of observations that need addressing:
1) If the `_runme.ml` file has an error, make does NOT fail.
2) The `_runme.cmi` and `_runme.cmo` are generated into the source tree for out-of-source builds. This is fundamentally wrong. These files are then moved into the build tree. The source tree might get contaminated if the mv fails. Also if the mv fails, the make should fail. Redirecting the mv output to /dev/null shouldn't be done, it makes debugging very hard in the event of errors! For in-source builds, the mv is unnecessary. All round, the output should go directly into the build tree, not the source tree.

Having said all that, it is great to see the output in Travis now as Travis does out-of-source builds. Without Travis working, OCaml was on the list of languages to be removed in the forthcoming 4.0.0 release as we are not going to maintain any languages that aren't properly setup for testing. So you may just save OCaml from the chop... big thanks.

**Comment by ZackerySpytz** [comment]
Thank you, @wsfulton, for the comments. I'll respond soon.

**Comment by ZackerySpytz** [comment]
> If the _runme.ml file has an error, make does NOT fail.

Actually, `make` did fail in this case, but for an unrelated reason: the OCaml compiler removes the `.cmo` file (if it exists) before generating a new one, and if compilation of the `*_runme.ml` fails, the missing `.cmo` file will end up causing a failure (this was far from preferable). It should properly fail now (for what it's worth, this was an issue with the preexisting code).

> Actually, the test-suite was working on Travis out-of-source builds

The test suite was not working for out-of-source builds. On Travis, (for example, https://travis-ci.org/swig/swig/jobs/471124176#L1187) one can see that runme tests fail with the following:
```
checking ocaml testcase class_ignore (with run test)
File "class_ignore.ml", line 93, characters 13-14:
Warning 11: this match case is unused.
File "_none_", line 1:
Error: Cannot find file ../../../../../Examples/test-suite/ocaml/class_ignore.cmo
```
 The changes in Examples/test-suite/ocaml/Makefile.in fix this.

> These messages no longer appear:

I added `-w -S` to temporarily disable them, as they fill up the build logs with cruft. The OCaml module needs to generate cleaner code, but I think the OCaml test suite should be fixed first.

**Comment by wsfulton** [comment]
Thanks for explanations. This certainly looks better now, so I'll merge it across. I had some problems initially as I tested with `-j8`. Probably it is a lurking issue that was always there. I've added this info to #364.

**Pull request merged**
