### PR TITLE
do not emit static const variables twice

### PR DESCRIPTION
**Pull request by mmomtchev**
It is an ugly solution, but it is low-risk and it works

#2534

### CODE REVIEW

**Comment by mmomtchev** [comment]
@ojwb @wsfulton what do you think of this PR, the problem it resolves is purely cosmetic since the V8 API accepts that a symbols is registered twice.

It is a real problem only with the NAPI backend where it has been solved separately (in the NAPI PR)?

**Comment by ojwb** [comment]
Yeah, the whole extra level of abstraction in `javascript.cxx` doesn't seem helpful.

As for you workaround, I was going to leave it to William to decide whether he was happy with it.

If we're going for it, I would suggest naming the attribute used with a `js_` or `javascript_` prefix for clarity and reduced risk of it colliding with future generic attributes.

**Comment by mmomtchev** [comment]
@ojwb this is ready

**Comment by ojwb** [comment]
> this is ready

As I already noted, I'd like wsfulton's thoughts on this.  He may see a cleaner way to solve it short of a major refactor of `javascript.cxx`.

**Comment by wsfulton** [comment]
We use `:` rather than `_` as a namespace separator in the attributes with the prefix the name of the file usually. So use "javascript:constant". BTW, the "hasconst" might be the existing attribute you can use rather than creating a new one. That's if I understand correctly that you want to detect the "static const" or "constexpr" variables.

**Comment by mmomtchev** [comment]
The problem is that the way the JS backend is structured. There is `enterVariable`, `variableHandler` and `exitVariable`. There is also a `constantHandler` which is called only for constants. The declaration is emitted in `exitVariable`. Constants can be created in two different ways - by a chain of

  `enterVariable` -> `constantHandler` -> `exitVariable`

when the syntax analysis detects a constant or also by a chain of

`enterVariable` -> `variableHandler` -> `enterVariable` -> `constantHandler` -> `exitVariable` -> `exitVariable`

when `variableHandler` switches a variable to a constant - which happens for class members that are `static const` and `static constexpr`. So I need a special flag to detect this second call of `exitVariable`. Otherwise I end up with two identical declarations. For JSC and V8 this is not a problem - if you look at the code you will see two consecutive statements creating the value, the second one overwriting the first one. But for the NAPI generator, it is a problem, because it creates a naming collision. The NAPI generator has its own solution. The question is whether this is needed for V8/JSC.

**Pull request closed without merging**
