### PR TITLE
Gsoc2012 objc

### PR DESCRIPTION
**Pull request by maxep**
Hi,

This PR merges master into gsoc2012-objc. 
It fixes a memory leak in objc.cxx and the objc configuration.
Examples pass on my osx but not on travis.
Test-suite is still broken for objc...

Regards,

Maxime

### CODE REVIEW

**Comment by wsfulton** [comment]
@maxep How come the memory leak is fixed by merging in master? To be honest, I'd rather not merge in master unless the tests pass as this is too big a change for me to review. I don't recall what the state of the testing was beforehand, so without that info, I can't be sure nothing has regressed. Really we need someone who can take responsibility for getting the tests passing with a longer term view of merging this branch into master. Would you consider taking that on?

**Comment by maxep** [comment]
Hi @wsfulton 

This PR is not for master but ```gsoc2012-objc``` branch. I just updated ```gsoc2012-objc``` to prepare further merge. 

This is the memory leak I found:
``` diff
--- a/Source/Modules/objc.cxx
+++ b/Source/Modules/objc.cxx

@@ -1097,13 +969,13 @@ void OBJECTIVEC::emitProxyGlobalFunctions(Node *n) {
 
   /* Write the function declaration to the proxy_h_code 
      and function definition to the proxy_mm_code */
-  if ((member_func_flag || member_constant_flag || Strcmp(storage, "friend") == 0 || Strcmp(storage, "typedef") == 0))
-  {
-  Printv(proxy_global_function_decls, function_decl, "\n", NIL);
-  Printv(proxy_global_function_defns, function_defn, "\n", NIL);
-  }else {
-  Printv(proxy_h_code, function_decl, "\n", NIL);
-  Printv(proxy_mm_code, function_defn, "\n", NIL);
+  if ((member_func_flag || member_constant_flag || Cmp(storage, "friend") == 0 || Cmp(storage, "typedef") == 0)) {
+    Printv(proxy_global_function_decls, function_decl, "\n", NIL);
+    Printv(proxy_global_function_defns, function_defn, "\n", NIL);
+  }
+  else {
+    Printv(proxy_h_code, function_decl, "\n", NIL);
+    Printv(proxy_mm_code, function_defn, "\n", NIL);
   }
   //Delete(paramstring);
   Delete(proxyfunctionname);
```
Function ```Strcmp``` crash if ```storage``` is null.

I did pass the test suite on the current state of the ```gsoc2012-objc``` and it fails on the same spot, I didnt notice any regression. I will try to fix the ci for objc.

Regards,

Maxime

**Comment by wsfulton** [comment]
Could you please post the output somewhere of the osx test-suite output before and after these changes? I'll merge them to the branch if there are no regressions, which I'll just check by doing a diff on the test-suite output. 

Can you also please restore the Travis testing back to how it was plus add in your osx testing? So it should just test objective c and nothing else. The linux testing using ```gnustep-devel gobjc++``` in .travis.yml has disappeared. You'll need to move it from the old .travis.yml into Tools/travis-linux-install.sh. Once this is done, I will be able to compare the original Travis test-suite results with your changes.

**Comment by maxep** [comment]
Hi @wsfulton 
The objc configuration for linux is still broken..
You will find attached the objc test-suite output on both gsoc2012-objc and my fork. I get it by running:
```
> ./autogen.sh && ./configure && make
> make check-objc-test-suite > swig_swig_gsoc2012-objc.txt 2>&1
```
[swig_swig_gsoc2012-objc.txt](https://github.com/swig/swig/files/81653/swig_swig_gsoc2012-objc.txt)
[maxep_swig_gsoc2012-objc.txt](https://github.com/swig/swig/files/81654/maxep_swig_gsoc2012-objc.txt)

**Comment by wsfulton** [comment]
There are a number of regressions when comparing the two files you posted, so I can't accept this. The merge introduces too much change to investigate deeper. I think the best way forward without too much effort is to provide one patch that shows the test-suite working on osx and travis. After that a subsequent patch with the memory leak fix will be easily reviewed and shown to not have any regressions. Only then does it make sense to look at working towards merging in master.

**Comment by maxep** [comment]
No worries, I understand there is too much to review. The `gsoc2012-objc` branch stayed as is for too long and the test suite significantly changed since. I tried to fix most of them while upgrading it, I will try to find time to continue..
Anyway, thanks for the good work!

**Pull request closed without merging**
