### PR TITLE
Add a batch of JS unit tests

### PR DESCRIPTION
**Pull request by mmomtchev**
This is the first batch of unit tests that pass without modifying the code

All of these tests are directly based on their Python counterparts

### CODE REVIEW

**Comment by ojwb** [comment]
@mmomtchev I like the approach of breaking up the changes for easier review.  However the JSC job failed in the tests which needs resolving before we can merge this.

**Comment by mmomtchev** [comment]
@ojwb In fact I did group them together exactly to avoid making tons of PRs
I plan to add as much as possible of the unit tests that exist for Python to JavaScript

**Comment by ojwb** [comment]
Sorry, I didn't express that at all clearly - I think you have the granularity about right.

I was trying to say it's good to have split off adding new `*_runme.js` for existing tests which pass without code changes, rather than just including this in one big PR with all your JS-related changes.

**Comment by ojwb** [comment]
Yes, and that's a good approach.

**Comment by mmomtchev** [comment]
In this case, can I ask you to not commit anymore my PRs from other accounts? I have been unemployed for the last 3 years, because my former employers reached an agreement with corrupt judges to stop a number of criminal complaints about a shocking sexual harassment affair that was linked to false rape accusation organized with the help of the French police. I have been living with a few bucks per day for more than an year, and I have to eat for no more than $2.50. I am hoping that I will be able to find a job where they won't extort me anymore and this work really helps me to have a hope to be able to eat normally.

**Comment by ojwb** [comment]
This change shows as authored by you in the git history (I've redacted email addresses):

```
$ git show --no-patch d25b288d8cb8ed89a645814451860cc54c1118a9
commit d25b288d8cb8ed89a645814451860cc54c1118a9
Author: Momtchil Momtchev <...>
Date:   Sun May 14 20:45:54 2023 +0200

    fix a copy & paste blunder
```

If you drill down, then the fuller metadata reports you as author and me as committer, which I guess is what you're referring to?

```
 git show --format=fuller --no-patch d25b288d8cb8ed89a645814451860cc54c1118a9
commit d25b288d8cb8ed89a645814451860cc54c1118a9
Author:     Momtchil Momtchev <...>
AuthorDate: Sun May 14 20:45:54 2023 +0200
Commit:     Olly Betts <...>
CommitDate: Tue May 23 18:05:58 2023 +1200

    fix a copy & paste blunder
```

I merged this PR via github, but setting committer like this also matches the behaviour of `git cherry-pick` on the command line.  It's certainly not me trying to take credit for your work.  It's just how git indicates that it was me that applied this change to the SWIG repo.

It's actually possible to override the committer from the command line, but (a) I'd have to remember to each time and (b) having the committer set correctly tells us who actually applied the change which could be useful information if someone later finds a problem with it, so overriding it doesn't seem a great idea.

Potential employers can clearly see you're listed as the author, and the author is the person who actually wrote something.

**Comment by mmomtchev** [comment]
@ojwb I think that the merge was done in a very unusual way, the commit is absent from the list of my commits and the code is definitely not identified as having been contributed by me. I work for free and I would really like to be able to get proper credit for everything I do. It is the case with absolutely every other commit besides this one.

**Comment by ojwb** [comment]
So which commit are you referring to?

And where does it show as now having been contributed by you?

I'm certainly not deliberately failing to credit anyone (and we're all working for free here) but it seems I've messed up somewhere and I'm sorry for that, but knowing where would likely help me understand what happened.

**Comment by mmomtchev** [comment]
These 22 unit tests: https://github.com/swig/swig/commit/5eedba422fa5caaf0272ee5115755df6b7def466

**Comment by ojwb** [comment]
OK, I think I must have merged that from the command line with `git merge --squash`.  It looks like that doesn't copy over authorship information even if all the squashed commits have the same author.  Sorry about that, I'll have to watch out for that.

**Comment by ojwb** [comment]
I'm really sorry, but the commit hash includes the commit metadata and also the commit hash of the parent commit so changing the author of a commit retrospectively would require rewriting the history of SWIG's git master from that commit on by force pushing it, and force pushing is one of those things you just don't do to the default branch of a public git repo because it's really disruptive to anyone working with the repo.

I really am going to try my hardest not to repeat this incident.

You could also point to https://github.com/swig/swig/pulls?q=is%3Aclosed+is%3Apr+author%3Ammomtchev to show all the PRs you've had merged, which is perhaps a better option than a list of commits anyway as there's more context about the changes but people can still click to see the commits if they want.

**Comment by mmomtchev** [comment]
@ojwb 
Ok, I will make it very clear. Before SWIG, during my unemployment, I used to contribute to various OpenJSF and OSGEO projects - mostly Node.js and GDAL. In all of these projects, progressively, it became absolutely impossible to work, because they doing things that, progressively, became absolutely impossible to write about in a Github issue. The situation worsened after each incident, because the root cause of what was happening was a very serious personal problem that is behind the very reason for the judicial extortion. In both projects it took several months before it reached this stage. Once this has started, it is impossible to stop - the person doing this will always be motivated to continue doing so - and the shame of the people in the project will be something out of this world.

I will continue submitting PRs - but I guarantee you that this situation is headed right in the same direction.

**Comment by mmomtchev** [comment]
In Node,js I have a huge PR for a GSoC project, with an important feature, that has been waiting for the last 6 months - because everytime someone reviews, there are people posting dicks, which makes it absolutely impossible to do any serious review. The very last time I did something on it, they were cancelling my running unit tests while posting things impossible to describe in a desperate effort to reverse the situation. I really hope that this won't happen in this project.

**Pull request closed without merging**
