### PR TITLE
Remove support for old Node.js versions and stand-alone v8

### PR DESCRIPTION
**Pull request by yegorich**
Start removing support for stand-alone v8 as also Node.js older than v6.x.

Fixes https://github.com/swig/swig/issues/1735.

### CODE REVIEW

**Comment by yegorich** [comment]
This PR doesn't fix all issues for the newer Node.js releases, but it is a good foundation that reduces code and makes new changes easier.

@wsfulton what are your plans for 4.0.2 and 4.1.0?

I already have a patch that extracts the minimum required changes from https://github.com/swig/swig/pull/1702 to successfully run examples and test-suite for Node.js v12.

**Comment by yegorich** [comment]
This is my local branch with preliminary v12 fixes: https://github.com/yegorich/swig/commits/v12-fixes

@nullr0ute could you try it and provide your build log? BTW Node.js v13 won't work, only v6 till v12.

**Comment by lissyx** [comment]
> @nullr0ute could you try it and provide your build log? BTW Node.js v13 won't work, only v6 till v12.

My changes does cover until v13, but you might need to look at this one: https://github.com/lissyx/swig/commit/5e1bdcfd6e5bd8353993433bd0efb4a3cb3ca639

**Comment by wsfulton** [comment]
Minimum supported version for swig-4.1 is Node v6, see #1746. Please update this patch accordingly and resubmit.

**Pull request closed without merging**
