### PR TITLE
Fix code generated for Ruby global variables

### PR DESCRIPTION
**Pull request by treitmayr**
This commit fixes swig#1653 by creating a Ruby virtual variable for a C/C++ global variable when SWIG is invoked with the -globalmodule option.

### CODE REVIEW

**Comment by treitmayr** [comment]
I tried to figure out why appveyor CI had failed, and I am pretty sure there is nothing about failing "check-python-examples" which this commit could have affected in a bad way. Still not sure what's going on there...

**Comment by vadz** [comment]
The AppVeyor failures definitely seem unrelated. I know they've recently updated their environment, so it could be due to a change in Python. In particular, comparing the log of the failed build with a recent successful one, I see this:
```
checking for 2to3... 2to3
```
in the old one but this
```
checking for 2to3... no
checking for 2to3.py... C:/Python36/Tools/scripts/2to3.py
```
so it looks like `2to3` used by SWIG tests doesn't work any longer.

**Comment by treitmayr** [comment]
Are there still refinements to be done to this PR? Please let me know as soon as it has been reviewed.

**Comment by vadz** [comment]
Sorry, I commented here, but just to explain the issue with `2to3` and I can't say anything else as I know nothing about Ruby module. FWIW it looks fine to me and the tests definitely help, so I would merge it, but I'm leaving the final decision to @wsfulton

**Comment by wsfulton** [comment]
Thanks for the patch. I've just started looking at this now. I'll finish checking it and then look at merging it in shortly.

I note that Ruby 1.9 and later that we test with in Travis work with this patch so there is no problem with older versions.

**Comment by wsfulton** [comment]
Below is a patch to check the values are correct in c++. What surprised me in writing this code is that when `-globalmodule` is being used, the C/C++ global function `check_values` becomes a Ruby global function. This seems to be an unexpected side effect??

```patch
From 715698d3489dbb3a858aeaffc0db49e43955413b Mon Sep 17 00:00:00 2001
From: William S Fulton <wsf@fultondesigns.co.uk>
Date: Mon, 23 Dec 2019 07:29:11 +0000
Subject: [PATCH] Ruby globalmodule variables test enhancement

Check that the variables values are as expected in C++.
Note that the check_values global function is global in Ruby when
using -globalmodule.
---
 Examples/test-suite/global_immutable_vars.i              | 9 +++++++++
 Examples/test-suite/global_immutable_vars_cpp.i          | 9 +++++++++
 .../test-suite/ruby/global_immutable_vars_cpp_runme.rb   | 1 +
 Examples/test-suite/ruby/global_immutable_vars_runme.rb  | 1 +
 .../ruby/ruby_global_immutable_vars_cpp_runme.rb         | 1 +
 .../test-suite/ruby/ruby_global_immutable_vars_runme.rb  | 1 +
 Examples/test-suite/ruby_global_immutable_vars.i         | 9 +++++++++
 Examples/test-suite/ruby_global_immutable_vars_cpp.i     | 9 +++++++++
 8 files changed, 40 insertions(+)

diff --git a/Examples/test-suite/global_immutable_vars.i b/Examples/test-suite/global_immutable_vars.i
index 608ec5661..2faf6b485 100644
--- a/Examples/test-suite/global_immutable_vars.i
+++ b/Examples/test-suite/global_immutable_vars.i
@@ -20,5 +20,14 @@
 %inline %{
   int global_mutable_var = 43;
   int specific_immutable_var = 44;
+
+  int check_values(int default_mutable, int global_immutable, int specific_mutable, int global_mutable, int specific_immutable) {
+    return
+      default_mutable    == default_mutable_var &&
+      global_immutable   == global_immutable_var &&
+      specific_mutable   == specific_mutable_var &&
+      global_mutable     == global_mutable_var &&
+      specific_immutable == specific_immutable_var;
+  }
 %}
 
diff --git a/Examples/test-suite/global_immutable_vars_cpp.i b/Examples/test-suite/global_immutable_vars_cpp.i
index ede3ec5e0..8ee3d8180 100644
--- a/Examples/test-suite/global_immutable_vars_cpp.i
+++ b/Examples/test-suite/global_immutable_vars_cpp.i
@@ -20,5 +20,14 @@
 %inline %{
   int global_mutable_var = 43;
   int specific_immutable_var = 44;
+
+  int check_values(int default_mutable, int global_immutable, int specific_mutable, int global_mutable, int specific_immutable) {
+    return
+      default_mutable    == default_mutable_var &&
+      global_immutable   == global_immutable_var &&
+      specific_mutable   == specific_mutable_var &&
+      global_mutable     == global_mutable_var &&
+      specific_immutable == specific_immutable_var;
+  }
 %}
 
diff --git a/Examples/test-suite/ruby/global_immutable_vars_cpp_runme.rb b/Examples/test-suite/ruby/global_immutable_vars_cpp_runme.rb
index c40896a86..7897f7da5 100644
--- a/Examples/test-suite/ruby/global_immutable_vars_cpp_runme.rb
+++ b/Examples/test-suite/ruby/global_immutable_vars_cpp_runme.rb
@@ -45,3 +45,4 @@ end
 swig_assert(had_exception, nil,
             "Global_immutable_vars_cpp::specific_immutable_var is writable (expected to be immutable)")
 
+swig_assert(Global_immutable_vars_cpp::check_values(80, 41, 82, 83, 44) == 1, nil, "Check values failed")
diff --git a/Examples/test-suite/ruby/global_immutable_vars_runme.rb b/Examples/test-suite/ruby/global_immutable_vars_runme.rb
index af55cfeb3..ffbea270f 100644
--- a/Examples/test-suite/ruby/global_immutable_vars_runme.rb
+++ b/Examples/test-suite/ruby/global_immutable_vars_runme.rb
@@ -49,3 +49,4 @@ end
 swig_assert(had_exception, nil,
             "Global_immutable_vars::specific_immutable_var is writable (expected to be immutable)")
 
+swig_assert(Global_immutable_vars::check_values(80, 41, 82, 83, 44) == 1, nil, "Check values failed")
diff --git a/Examples/test-suite/ruby/ruby_global_immutable_vars_cpp_runme.rb b/Examples/test-suite/ruby/ruby_global_immutable_vars_cpp_runme.rb
index 8453254eb..5523b59f4 100644
--- a/Examples/test-suite/ruby/ruby_global_immutable_vars_cpp_runme.rb
+++ b/Examples/test-suite/ruby/ruby_global_immutable_vars_cpp_runme.rb
@@ -45,3 +45,4 @@ end
 swig_assert(had_exception, nil,
             "$specific_immutable_var is writable (expected to be immutable)")
 
+swig_assert(check_values(80, 41, 82, 83, 44) == 1, nil, "Check values failed")
diff --git a/Examples/test-suite/ruby/ruby_global_immutable_vars_runme.rb b/Examples/test-suite/ruby/ruby_global_immutable_vars_runme.rb
index fda1ccf0f..45a8506ba 100644
--- a/Examples/test-suite/ruby/ruby_global_immutable_vars_runme.rb
+++ b/Examples/test-suite/ruby/ruby_global_immutable_vars_runme.rb
@@ -49,3 +49,4 @@ end
 swig_assert(had_exception, nil,
             "$specific_immutable_var is writable (expected to be immutable)")
 
+swig_assert(check_values(80, 41, 82, 83, 44) == 1, nil, "Check values failed")
diff --git a/Examples/test-suite/ruby_global_immutable_vars.i b/Examples/test-suite/ruby_global_immutable_vars.i
index dc49cd946..6f067d269 100644
--- a/Examples/test-suite/ruby_global_immutable_vars.i
+++ b/Examples/test-suite/ruby_global_immutable_vars.i
@@ -21,5 +21,14 @@
 %inline %{
   int global_mutable_var = 43;
   int specific_immutable_var = 44;
+
+  int check_values(int default_mutable, int global_immutable, int specific_mutable, int global_mutable, int specific_immutable) {
+    return
+      default_mutable    == default_mutable_var &&
+      global_immutable   == global_immutable_var &&
+      specific_mutable   == specific_mutable_var &&
+      global_mutable     == global_mutable_var &&
+      specific_immutable == specific_immutable_var;
+  }
 %}
 
diff --git a/Examples/test-suite/ruby_global_immutable_vars_cpp.i b/Examples/test-suite/ruby_global_immutable_vars_cpp.i
index cf3145e80..511390e20 100644
--- a/Examples/test-suite/ruby_global_immutable_vars_cpp.i
+++ b/Examples/test-suite/ruby_global_immutable_vars_cpp.i
@@ -19,5 +19,14 @@
 %inline %{
   int global_mutable_var = 43;
   int specific_immutable_var = 44;
+
+  int check_values(int default_mutable, int global_immutable, int specific_mutable, int global_mutable, int specific_immutable) {
+    return
+      default_mutable    == default_mutable_var &&
+      global_immutable   == global_immutable_var &&
+      specific_mutable   == specific_mutable_var &&
+      global_mutable     == global_mutable_var &&
+      specific_immutable == specific_immutable_var;
+  }
 %}
 
-- 
2.17.1

```

**Comment by treitmayr** [comment]
My understanding is that generating global Ruby functions for global C/C++ functions is exactly the intended behavior when doing the conversion with `-globalmodule`. However this has not changed in any way by my PR.

I second your additions to the test cases which additionally check the expected values in the C/C++ world.

**Comment by treitmayr** [comment]
I am afraid this PR is affected by issue #1689 for Ruby 2.7, too. Due to deprecating the function signature to be used until Ruby 2.6 (see [include/ruby/backward/cxxanyargs.hpp](https://github.com/ruby/ruby/blob/ruby_2_7/include/ruby/backward/cxxanyargs.hpp#L66-L75)) the adapted solution will have to differentiate between Ruby versions before vs. starting with 2.7.
Will take a look at it as soon as I find some time.

**Comment by wsfulton** [comment]
My bad, I was under the impression from your changes to Ruby.html that this only affected global variables, but the existing docs make it clear that everything is wrapped into the global module when using `-globalmodule`.

**Comment by wsfulton** [comment]
Please adjust #1692 after this merge if necessary.

**Comment by treitmayr** [comment]
I would have added your extensions to the test cases as shown above but hesitated due to the missing support for Ruby 2.7. Now that support for 2.7 can be added via PR #1692 your test extension got missed.

**Comment by wsfulton** [comment]
Patch above containing additional testing has been committed as 558f0ba485702d2c2146640e345ba39da3847deb

**Pull request merged**
