### PR TITLE
fix for nested ignored types

### PR DESCRIPTION
**Pull request by wkalinin**

### CODE REVIEW

**Comment by wsfulton** [comment]
Looks okay to me. Could you pop in the testcase with the patch please?

**Comment by wkalinin** [comment]
added test

**Comment by wsfulton** [comment]
@wkalinin did you see the test failed?

**Comment by wkalinin** [comment]
Sorry, took it verbatim from Vadim's patch and forgot to look at the results.

**Comment by wkalinin** [comment]
The test still fails under 'go', but I have no idea why. PHP and Python Travis fails seem to be unrelated to this case.

**Comment by wkalinin** [comment]
Found the cause of 'go' fail -  the name of the module in the test should be the same as the file name.
Now the only platform failing is Octave 3.8, but it fails not on this test but before the tests start.

**Comment by wsfulton** [comment]
Travis fails sometimes with network errors like this. I've restarted this Octave test.

**Pull request merged**
