### PR TITLE
Add Duktape JS support to SWIG

### PR DESCRIPTION
**Pull request by affixalex**
I don't think this is ready to merge yet, but it is to a point where I could use some code review. This was my first experience with SWIG! The `NewPointerObj` and `ConvertPtr` functions aren't right yet, and the configure script logic may also be incorrect.

https://github.com/hypoalex/dukswig - I've been developing against the tests out-of-tree, so the duk_shell.cxx file doesn't actually work as intended yet to run the test harness in the tree. I'd love to get some input about conventions for embedded runtimes like Duktape, it currently looks for a shared library and header which I felt was somewhat convenient for development.

Again, I'm just hoping for some review and feedback!

I'll be happy to get this up to par and get it into the tree.

Thanks!

### CODE REVIEW

**Comment by hypoalex** [comment]
There is more cleanup and dead code removal to be done here, along with setting up the Travis-CI in a way that is reasonably sane (there are no Ubuntu Duktape packages). However, if `libduktape.so`, `duk_config.h` and `duktape.h` are in your library and header search paths, then `make check-javascript-examples ENGINE=duk` should pass all tests on Linux and OSX.

**Comment by hypoalex** [comment]
The test suite is current passing at around 97%. I've done a bit of code hygiene here (I just find these type of block comments much more readable), but I'm having a bit of issue with the code emission, essentially this is emitting blocks to reuse temporary variable names within functions and enums aren't available within those scopes.

If anyone has any input on this, I'd be very appreciative!

**Comment by hypoalex** [comment]
The test suite and examples all build, run, and pass now. This wasn't developed with `-std=c89 -Werror`, the issues due to that are the only remaining problems with this.

**Comment by wsfulton** [comment]
hi, if the test-suite passes 100% on Travis, I'll do a thorough review. Looks like this will require fixes for C89 and fixing a few testcases.
Can you change all usage of duk to duktape... (variable names, directory and file names) I don't like shortened names. I did a super quick scan and can't see any obvious problems other than there is no documentation, for which I'll comprehensive docs to get started on the review.

**Comment by wsfulton** [comment]
Can you also please make sure the code has been beautified with 'make beautify' too.

**Comment by hypoalex** [comment]
Sure, thanks! I'm a little busy this week but I'll try to get to this over
the weekend.

**Comment by wsfulton** [comment]
Hi, @hypoalex. We are going to make swig-4.0 the next version of SWIG. Will you be continuing on this Javascript module for inclusion in 4.0?

**Comment by hypoalex** [comment]
This doesn't need much work, and I've been meaning to get to it but yes... I'd love to get this merged. I need to add support for Duktape 2.x (fairly trivial ifdeffery) and do the C89 backporting which (I believe) was just hoisting variable declarations out of loops.

**Comment by wsfulton** [comment]
No activity. Any new module to be added to SWIG requires an active module maintainer, so closing this request.

**Pull request closed without merging**
