### PR TITLE
csharp: Added std_unordered_map.i

### PR DESCRIPTION
**Pull request by emmenlau**
This PR adds support for std_unordered_map to csharp.

### CODE REVIEW

**Comment by SimonBoorer** [comment]
Thanks for this! I modified it slightly to add support for hash functions:
```
- --- std_unordered_map.i.orig	2023-03-07 12:20:03.057233900 +0000
- +++ std_unordered_map.i	2023-03-03 12:14:14.439337400 +0000
- @@ -1,7 +1,7 @@
-  /* -----------------------------------------------------------------------------
-   * std_unordered_map.i
-   *
- - * SWIG typemaps for std::unordered_map< K, T >
- + * SWIG typemaps for std::unordered_map< K, T, H >
-   *
-   * The C# wrapper is made to look and feel like a C# System.Collections.Generic.IDictionary<>.
-   *
- @@ -24,9 +24,9 @@
-  %}
-  
-  /* K is the C++ key type, T is the C++ value type */
- -%define SWIG_STD_UNORDERED_MAP_INTERNAL(K, T)
- +%define SWIG_STD_UNORDERED_MAP_INTERNAL(K, T, H)
-  
- -%typemap(csinterfaces) std::unordered_map< K, T > "global::System.IDisposable \n    , global::System.Collections.Generic.IDictionary<$typemap(cstype, K), $typemap(cstype, T)>\n"
- +%typemap(csinterfaces) std::unordered_map< K, T, H > "global::System.IDisposable \n    , global::System.Collections.Generic.IDictionary<$typemap(cstype, K), $typemap(cstype, T)>\n"
-  %proxycode %{
-  
-    public $typemap(cstype, T) this[$typemap(cstype, K) key] {
- @@ -228,7 +228,7 @@
-      void clear();
-      %extend {
-        const mapped_type& getitem(const key_type& key) throw (std::out_of_range) {
- -        std::unordered_map< K, T >::iterator iter = $self->find(key);
- +        std::unordered_map< K, T, H >::iterator iter = $self->find(key);
-          if (iter != $self->end())
-            return iter->second;
-          else
- @@ -240,19 +240,19 @@
-        }
-  
-        bool ContainsKey(const key_type& key) {
- -        std::unordered_map< K, T >::iterator iter = $self->find(key);
- +        std::unordered_map< K, T, H >::iterator iter = $self->find(key);
-          return iter != $self->end();
-        }
-  
-        void Add(const key_type& key, const mapped_type& value) throw (std::out_of_range) {
- -        std::unordered_map< K, T >::iterator iter = $self->find(key);
- +        std::unordered_map< K, T, H >::iterator iter = $self->find(key);
-          if (iter != $self->end())
-            throw std::out_of_range("key already exists");
-          $self->insert(std::pair< K, T >(key, value));
-        }
-  
-        bool Remove(const key_type& key) {
- -        std::unordered_map< K, T >::iterator iter = $self->find(key);
- +        std::unordered_map< K, T, H >::iterator iter = $self->find(key);
-          if (iter != $self->end()) {
-            $self->erase(iter);
-            return true;
- @@ -261,21 +261,21 @@
-        }
-  
-        // create_iterator_begin(), get_next_key() and destroy_iterator work together to provide a collection of keys to C#
- -      %apply void *VOID_INT_PTR { std::unordered_map< K, T >::iterator *create_iterator_begin }
- -      %apply void *VOID_INT_PTR { std::unordered_map< K, T >::iterator *swigiterator }
- +      %apply void *VOID_INT_PTR { std::unordered_map< K, T, H >::iterator *create_iterator_begin }
- +      %apply void *VOID_INT_PTR { std::unordered_map< K, T, H >::iterator *swigiterator }
-  
- -      std::unordered_map< K, T >::iterator *create_iterator_begin() {
- -        return new std::unordered_map< K, T >::iterator($self->begin());
- +      std::unordered_map< K, T, H >::iterator *create_iterator_begin() {
- +        return new std::unordered_map< K, T, H >::iterator($self->begin());
-        }
-  
- -      const key_type& get_next_key(std::unordered_map< K, T >::iterator *swigiterator) {
- +      const key_type& get_next_key(std::unordered_map< K, T, H >::iterator *swigiterator) {
-          (void)self;
- -        std::unordered_map< K, T >::iterator iter = *swigiterator;
- +        std::unordered_map< K, T, H >::iterator iter = *swigiterator;
-          (*swigiterator)++;
-          return (*iter).first;
-        }
-  
- -      void destroy_iterator(std::unordered_map< K, T >::iterator *swigiterator) {
- +      void destroy_iterator(std::unordered_map< K, T, H >::iterator *swigiterator) {
-          (void)self;
-          delete swigiterator;
-        }
- @@ -293,7 +293,7 @@
-  
-  // Default implementation
-  namespace std {
- -  template<class K, class T > class unordered_map {
- -    SWIG_STD_UNORDERED_MAP_INTERNAL(K, T)
- +  template<class K, class T, class H = std::hash<K> > class unordered_map {
- +    SWIG_STD_UNORDERED_MAP_INTERNAL(K, T, H)
-    };
-  }
- 
```

**Comment by wsfulton** [comment]
The patch will need a testcase in order to be accepted. I think this will be quite easy though. There is a testcase already at [cpp11_std_unordered_map.i](https://github.com/swig/swig/blob/master/Examples/test-suite/cpp11_std_unordered_map.i) and you can pick appropriate bits out of the std_map runtime testcase [li_std_map_runme.cs](https://github.com/swig/swig/blob/master/Examples/test-suite/csharp/li_std_map_runme.cs) or perhaps take further inspiration or convert the Java runtime test  [li_std_map_runme.java](https://github.com/swig/swig/blob/master/Examples/test-suite/java/li_std_map_runme.java).

**Comment by wsfulton** [comment]
`$self` should be used instead of `self`. Similar to comment in #2479.

**Comment by christophe-calmejane** [comment]
This file is taken from https://github.com/microsoft/CNTK/blob/master/bindings/csharp/Swig/std_unordered_map.i
Not sure about the copyright notice.

**Comment by wsfulton** [comment]
Contributions to the Lib directory do not have a copyright notice as they are in the SWIG library, and from https://swig.org/legal.html:

> the SWIG library which is permissively licensed to be redistributed without restriction

**Comment by emmenlau** [comment]
> This file is taken from https://github.com/microsoft/CNTK/blob/master/bindings/csharp/Swig/std_unordered_map.i Not sure about the copyright notice.

@christophe-calmejane I'm sorry but why would you say that? It is not true!!! I developed `std_unordered_map.i` from `std_map.i` by replacing the relevant modifiers. I did not even know that the other file exists and have never seen it in my life (until just now). If you run a diff between swig `std_unordered_map.i` and `std_map.i` it will be much much smaller than a diff between the version you pointed out.

It is possible that both files share a similar ancestry, but this is beyond my knowledge and pure guessing.

**Comment by christophe-calmejane** [comment]
No harm was intended, I was just wondering about (c) issues since the 2 files are almost exactly identical and the other one was older. If it's the same as the official `std::map.i` then it makes sense the files are pretty much the same. Sorry about the confusion.

Anyhow it looks like there is no copyright text in the other repository, so I guess it's all ok.

Regarding the actual file, I tried Simon's version (after changing to `$self`) and it looks fine.

**Comment by emmenlau** [comment]
> No harm was intended

Ok. Its good that you pointed out the possible problem! But licensing and copyright are sensitive issues, so better not judge.

**Comment by emmenlau** [comment]
> Thanks for this! I modified it slightly to add support for hash functions:

Thanks a lot @SimonBoorer . I have integrated your changes in the latest version that I will push ASAP.

**Comment by wsfulton** [comment]
Still needs a testcase as mentioned before.

**Comment by wsfulton** [comment]
Testcase added is in cb9d53b8bea47a4411e3fac04ef61bc8e84e9d4e

**Pull request merged**
