### PR TITLE
Add travis test for node 9

### PR DESCRIPTION
**Pull request by nshmyrev**
Pull request to demonstrate node 9 is broken in travis. Related to https://github.com/swig/swig/pull/968#issuecomment-370918993

### CODE REVIEW

**Comment by ojwb** [comment]
Thanks.

This shows CI as failing but that's only because I cancelled all the irrelevant pending builds to get the one we care about to run sooner - the `TRAVIS_NODE_VERSION="9"` build passed.

It would be great to get this working, but while you try to do that I'd suggest removing all the other builds from `.travis.yml` on your branch to avoid a lot of unnecessary work for the builders, and to get the build we care about run sooner.  Once we have a build actually using the newer node it'll be easy to splice the relevant changes in.

**Comment by wsfulton** [comment]
@nshmyrev, this will be useful when added properly. Any Travis development should be done using your own github account and then when working added as a pull request. My experience is that it takes quite a few commits to get any Travis specific changes working as you can't replicate the Travis yaml etc outside of Travis. You definitely don't want to run all 76 builds while you experiment on just one of them. Can you show the output of your own Travis account for me to look at to see if it really is running the right version of Node?

**Comment by wsfulton** [comment]
@nshmyrev what was your thinking when you changed .travis.yml to add in TRAVIS_NODE_VERSION="9"? The version in the build log is still:
```
showing javascript version
Node.js: v0.10.25
node-gyp: v0.10.10
```
Did you perhaps forget to add in code to travis_linux_install.sh to trigger off this? Details are in #968.

**Comment by wsfulton** [comment]
Superceded by #1290

**Pull request closed without merging**
