### PR TITLE
Add C++11 alias templates

### PR DESCRIPTION
**Pull request by liorgold**
Add support for C++11 alias templates such as:

```
template <typename T>
using Vec = std::vector<T>;
```

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by jschueller** [comment]
this seems worth looking at, anyone for a review ?

**Comment by wsfulton** [comment]
I'll review it in the next few days

**Comment by wsfulton** [comment]
Nice patch @liorgold, I feel this fills in the one last important C++11 feature that is missing in SWIG. There is just change that is needed and that is the "decl" attribute is empty and does not contain the declarator. This shouldn't be hard to fix though. You can see this if you compare an equivalent type alias, template alias and a typedef...
```swig
%inline %{
template<typename T, size_t N>
struct AliasingTest {
  T t;
  int n[N];
};

template<typename T> using AliasingTestInt5 = AliasingTest<T, 5>*;
using AliasingTestInt6 = AliasingTest<int, 6>*;
typedef AliasingTest<int, 7>* AliasingTestInt7;
%}

%template() AliasingTestInt5<int>;
%template(AliasingTestInt5Java) AliasingTest<int, 5>;
%template(AliasingTestInt6Java) AliasingTest<int, 6>;
%template(AliasingTestInt7Java) AliasingTest<int, 7>;

%inline %{
void alias5(AliasingTestInt5<int> t) { AliasingTest<int, 5>* x = t; }
void alias6(AliasingTestInt6 t) {}
void alias7(AliasingTestInt7 t) {}
%}
```
The output of using "-debug-module 1" is:
```
+++ template - 0x2b4b69f795b0 ----------------------------------------
| templatetype - "cdecl"
| name         - "AliasingTestInt5"
| sym:symtab   - 0x2b4b69f08990
| aliastemplate - "1"
| sym:name     - "AliasingTestInt5"
| decl         - ""
| feature:java:enum - "typesafe"
| type         - "p.AliasingTest<(T,5)>"
| sym:overname - "__SWIG_0"
| storage      - "typedef"
| templateparms - 0x2b4b69f79450
| 
+++ cdecl - 0x2b4b69f798d0 ----------------------------------------
| name         - "AliasingTestInt6"
| sym:symtab   - 0x2b4b69f08990
| kind         - "typedef"
| sym:name     - "AliasingTestInt6"
| decl         - ""
| feature:java:enum - "typesafe"
| type         - "p.AliasingTest<(int,6)>"
| sym:overname - "__SWIG_0"
| storage      - "typedef"
| typealias    - "1"
| 
+++ cdecl - 0x2b4b69f79b90 ----------------------------------------
| sym:name     - "AliasingTestInt7"
| name         - "AliasingTestInt7"
| decl         - "p."
| storage      - "typedef"
| kind         - "typedef"
| type         - "AliasingTest<(int,7)>"
| feature:java:enum - "typesafe"
| sym:symtab   - 0x2b4b69f08990
| sym:overname - "__SWIG_0"
| 
```
The decl attribute should be "p." in all 3 cases. This is an oversight in the non-template type aliasing implementation too.

**Comment by liorgold** [comment]
Thanks. I pushed a commit that should fix this issue.

**Comment by jschueller** [comment]
thank you!

**Pull request merged**
