### PR TITLE
Attempting fixes for Octave shared_ptr support

### PR DESCRIPTION
**Pull request by ConroyJ**
I have been working on trying to get shared_ptr's to work with Octave.  The test script and the optional extra command line arguments were based/borrowed from Kris Thielemans in the discussion found here:

http://comments.gmane.org/gmane.comp.programming.swig.devel/22094

For most of the changes, the Python equivalent files were used as examples to start from.
The specific test case completes without problems, and no issues were noticed when running through the octave test-suite checks.

The 'new' octave test script: Examples/test-suite/octave/li_boost_shared_ptr_runme.m

### CODE REVIEW

**Comment by ConroyJ** [comment]
@kwwette would you mind checking this out when you get a chance?  Thanks!

**Comment by kwwette** [comment]
One minor issue is that you haven't documented the -cppcast/-nocppcast options in the usage string at the top of octave.cxx.

Otherwise I don't see any obvious Octave problems, and it looks like the CI build passed. However I'm not very familiar with shared_ptr support in SWIG, so you should probably ask someone more familiar for a review, e.g. @wsfulton

**Comment by ConroyJ** [comment]
Usage string updated, thanks!

Believe this fix can close the ancient bug:
http://sourceforge.net/p/swig/bugs/1277/

**Comment by ConroyJ** [comment]
Usage string updated, thanks @kwwette  !

Believe this fix can close the ancient bug:
http://sourceforge.net/p/swig/bugs/1277/

How does this look @wsfulton  ?

**Comment by wsfulton** [comment]
Looks good to me.

**Pull request merged**
