### PR TITLE
implement shared_ptr in JavaScript

### PR DESCRIPTION
**Pull request by mislavn**
I want to add shared_ptr functionality to SWIG 4.0, this PR is based on #236.

Currently the JavaScript bindings compile but the destructors are not called and I need to add unit test requested in #236. Any help with this is appreciated.

### CODE REVIEW

**Comment by wsfulton** [comment]
Hi @mislavn. Did you see that this patch breaks the Javascript tests-suite? Can you fix the regressions first and foremost?

**Comment by mislavn** [comment]
OK, I'll work on this next month.

**Comment by wsfulton** [comment]
Ping @mislavn, Just to let you know the window for getting this into 4.0.0 is fast running out. Needs to be ready this month at the latest.

**Comment by fattredd** [comment]
Any updates on this?

**Comment by wsfulton** [comment]
I'm afraid this patch needs updating to support some compatibility changes in SWIG to support newer versions of Node.

**Pull request closed without merging**
