### PR TITLE
Fix bogus warnings about illegal dtor names for dtors of nested classes inside templates

### PR DESCRIPTION
**Pull request by vadz**
The import commit here is the second one, the first one is just some trivial cleanup. The changes in the second commit are actually rather small too, just view it ignoring whitespace so that the indented code doesn't appear as being changed.

### CODE REVIEW

**Comment by vadz** [comment]
I'm not sure if this has anything to do with Vladimir Kalinin's changes, I think this place was just not updated (because how could anybody know that it had to be updated?), but any additional review would be welcome, of course.

And the `nested_in_template` test case does indeed generate this warning without this PR. So I'd prefer to apply this one too when I'll merge the other one if you don't mind (I'll address your comments there a.s.a.p. but not today).

**Comment by wkalinin** [comment]
Indeed these changes have nothing to do with mine. That is, I just didn't notice this case. The fix seems to be fine as far as I can understand, and it is very localized anyway, doing exactly what's described.

**Comment by vadz** [comment]
@wsfulton Is it ok for me to merge this too?

**Comment by wsfulton** [comment]
This fixes more than a bogus warning. The destructor wrapper was missing altogether before the fix. Looks like it occurred for any nested class within a template, but only when the destructor was explicitly declared. That is, there was no problem with an implicit destructor. I've just merged this in, thanks.

@wkalinin. I'm also surprised we didn't find this case when the nested class support was added... never mind!

**Pull request merged**
