### PR TITLE
Remove obsolete js support

### PR DESCRIPTION
**Pull request by ojwb**
As noted in https://github.com/swig/swig/pull/2011#issuecomment-983962590 this can all be cleaned up now.

### CODE REVIEW

**Comment by ojwb** [comment]
"CI / ruby 2.6 gcc (pull_request)" failed, but is also failing on master.  "CI / ruby 2.6 gcc (push)" was OK.

No idea what's up but nothing Ruby-related is changed here and the failure isn't new, so I'm going to ignore this.

**Comment by ojwb** [comment]
Oh, and appveyor doesn't test javascript, so no point waiting on that to run.

**Comment by wsfulton** [comment]
Ruby 2.6 often fails unfortunately :(

**Comment by vadz** [comment]
> Ruby 2.6 often fails unfortunately :(

FWIW I think there is a real bug in SWIG-generated code, but I just didn't have time to track it down. Using an ASAN-enabled build of Ruby (or maybe just Valgrind?) should help understanding where does it come from.

**Comment by kkaempf** [comment]
> Ruby 2.6 often fails unfortunately :(

Fails in GH actions or during `make check` ?

**Comment by kkaempf** [comment]
I can't reproduce this crash locally (with rvm + Ruby 2.6.9, gcc 11.2.1) 🤔

**Comment by wsfulton** [comment]
I eventually replicated this problem and have raised it as an issue in #2115. @kkaempf if you got any ideas for a fix, can you please comment on this new issue.

**Pull request merged**
