### PR TITLE
Python use MSVC from older GitHub Windows 2019

### PR DESCRIPTION
**Pull request by erezgeva**
Once VC++ issue is resolved we can revert.

### CODE REVIEW

**Comment by erezgeva** [comment]
The same errors appears in AppVeyor

[SWIGLANG=python, VSVER=17, VER=310, APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2022](https://ci.appveyor.com/project/swig/swig/builds/50555937/job/kb644va9x4s3sb6y)
Failed in 21 min 59 sec
[SWIGLANG=python, VSVER=17, VER=310, Platform=x86, APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2022](https://ci.appveyor.com/project/swig/swig/builds/50555937/job/r5bc2e57n1ylcadq)
Failed in 24 min 37 sec

**Comment by wsfulton** [comment]
committed in dda6f691e58472ce2fad7278c1e8436030977024.

Surely there must be a way to use the older docker images that https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md provides. Docker images don't usually just disappear! @erezgeva, perhaps try and search or ask on some support forums.

**Comment by erezgeva** [comment]
> committed in [dda6f69](https://github.com/swig/swig/commit/dda6f691e58472ce2fad7278c1e8436030977024).
> 
> Surely there must be a way to use the older docker images that https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md provides. Docker images don't usually just disappear! @erezgeva, perhaps try and search or ask on some support forums.

I have no idea if it possible.

Seems AppVeyor upgrade their Windows in a similar way.

**Comment by erezgeva** [comment]
> committed in [dda6f69](https://github.com/swig/swig/commit/dda6f691e58472ce2fad7278c1e8436030977024).
> 
> Surely there must be a way to use the older docker images that https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md provides. Docker images don't usually just disappear! @erezgeva, perhaps try and search or ask on some support forums.

The image runs as virtual machine, not as a Docker container image.
I did search if I can create a Docker container image out of the runner image, and fail to find any reference on it.

**Comment by wsfulton** [comment]
Could you ask Github support how one can use an older version if (and when in this case) there is a bug in the toolsets provided (visual c++) in a new VM? Uninstalling and re-installing a different version of visual c++ on the fly doesn't seem like a viable workaround option as you pointed out.

**Comment by erezgeva** [comment]
> Could you ask Github support how one can use an older version if (and when in this case) there is a bug in the toolsets provided (visual c++) in a new VM? Uninstalling and re-installing a different version of visual c++ on the fly doesn't seem like a viable workaround option as you pointed out.

I open a bug report:
https://github.com/actions/runner-images/issues/10575

From the questions, it does not seems they provide an option to use older images.
I think the way to avoid such is to create our own Docker images.

**Pull request closed without merging**
