### PR TITLE
[C#] Fix memory leak in directorin typemap for std::string.

### LINKED ISSUE #998: Memory leak with director, csharp, std::string and sending strings to c#
## SWIG.i

```c++
%{
#include "net_invoker.h"
%}

%feature("director") NetInvokerBase;

class NetInvokerBase {
public:
    virtual ~NetInvokerBase() {}
    virtual const NetMethodInfo* GetMethodInfo(std::string tt)
    {
        return NULL;
    }
};

class NetInvoker {
public:
  static void set(NetInvokerBase* invoker) { NetInvoker::invoker = invoker; }
  static void reset() { NetInvoker::invoker = 0; }
private:
  static NetInvokerBase *invoker;
};
```

## C#

```c#
public class RuntimeNetInvoker : Qt.NetCore.NetInvokerBase
{
    public override bool IsValidType(string type)
    {
        return true;
    }

    public override NetMethodInfo GetMethodInfo(string tt)
    {
        return null;
    }
}

NetInvoker.set(new RuntimeNetInvoker());
```

## C++

```c++
std::string netType = "test";
NetInvoker::invoker->GetMethodInfo(netType);
```

This problem goes away if I take out the ```std::string``` parameter to ```GetMethodInfo```. So, this told me the issue is somewhere in the generated c++ code that marshals the ```std::string``` to the c# callback.

Here was the original code that was generated.

```c++
NetMethodInfo const *SwigDirector_NetInvokerBase::GetMethodInfo(std::string tt) {
  NetMethodInfo *c_result = 0 ;
  void * jresult = 0 ;
  char * jtt  ;
  
  if (!swig_callbackGetMethodInfo) {
    return NetInvokerBase::GetMethodInfo(tt);
  } else {
    jtt = SWIG_csharp_string_callback((&tt)->c_str());
    jresult = (void *) swig_callbackGetMethodInfo(jtt);
    c_result = (NetMethodInfo *)jresult; 
  }
  return (NetMethodInfo const *)c_result;
}
```

If I take out the ```SWIG_csharp_string_callback``` call, and passed the string directly to ```swig_callbackGetMethodInfo```, everything works, and the memory leak is gone.

So, changing the generated wrapper to this, resolved it.

```c#
NetMethodInfo const *SwigDirector_NetInvokerBase::GetMethodInfo(std::string tt) {
  NetMethodInfo *c_result = 0 ;
  void * jresult = 0 ;
  char * jtt  ;
  
  if (!swig_callbackGetMethodInfo) {
    return NetInvokerBase::GetMethodInfo(tt);
  } else {
    //jtt = SWIG_csharp_string_callback((&tt)->c_str());
    jresult = (void *) swig_callbackGetMethodInfo((&tt)->c_str());
    c_result = (NetMethodInfo *)jresult; 
  }
  return (NetMethodInfo const *)c_result;
}
```
How do I resolve this? I suspect the issue is somewhere in ```%include "std_string.i"```. for c#.

I am using swig 3.0.8, fresh from the Ubuntu repos.

### PR DESCRIPTION
**Pull request by ojwb**
Fixes #998

### CODE REVIEW

**Comment by ojwb** [comment]
All the CI jobs for csharp had passed so merged.

**Comment by wsfulton** [comment]
These changes were only made for `std::string` and not `const std::string&`. Is there a reason or is it just an oversight?

**Comment by wsfulton** [comment]
I can't find a C# runtime test in this area in our test-suite and I really think we need one if we're changing this because the marshalling of strings in the CLR is complete black magic, undocumented by Microsoft and not consistent across platforms. The leaks reported in the SWIG issues were only for Linux and not Windows, which makes me wonder if the new solution will actually be okay on Windows (which of course is the primary C# platform).

**Comment by wsfulton** [comment]
I'll look at adding in some C# runtime tests for these directors.

**Comment by ojwb** [comment]
> These changes were only made for `std::string` and not `const std::string&`. Is there a reason or is it just an oversight?

Sorry, I just turned the suggested patch in #998 into a PR (as you'd suggested the submitter do years ago but they never followed through).  No deep reason for not addressing the const ref case.

**Comment by wsfulton** [comment]
`const std::string&` done now in 8e4868af75f4f5fd0c60a41cae92763ac8110e79

**Comment by wsfulton** [comment]
BTW, I verified there is one less memory leakage with the patch on linux using valgrind. I couldn't determine this on Windows: drmemory bombed out. The added examples at least run on Windows, so hopefully all okay.

**Pull request merged**
