### PR TITLE
pep257 & numpydoc conforming docstrings

### PR DESCRIPTION
**Pull request by xantares**
minor python docstrings syntax fixes reported by pep257 (https://github.com/GreenSteam/pep257):
- mono-line module docsstring
- rewrite autodoc parameters section in numpydoc style (https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)
- on-line summary should end with "."
- adds a blank line after class docstring

I couldn't enable pep257 checks like we do for pep8 as too few tests check docstrings and too many warnings would have to be disabled, but maybe it's best as my pep8 changes may have broken the build for some users

### CODE REVIEW

**Comment by wsfulton** [comment]
@xantares, the branch from which this pull request originates no longer exists. Was this intentional? I can apply the patch in the pull request rather than merge it if okay with you?

**Comment by xantares** [comment]
Yes, please apply the patch.
I thought I had no more PR and deleted my repo.

**Comment by wsfulton** [comment]
@xantares please check this with the pep257 tool as I had lots of conflicts during the merge into master.

**Comment by xantares** [comment]
@wsfulton just checked, it's all good

**Pull request closed without merging**
