### PR TITLE
Fix broken tests for python3 -relativeimport and no -py3

### PR DESCRIPTION
**Pull request by mromberg**
Converts the test for python3 support from a swigtime check of py3 to a runtime check of the python version number.  The exact same import syntax is still used.  But now the test for python3 is done at the time the module is imported.

  This allows the .py file to work (with the -relativeimport switch) with both python2 and python3.

### CODE REVIEW

**Comment by wsfulton** [comment]
Thanks. I made a few additions:
- Added print statements to all import_packages runme files to easier track the examples (use ```make -s``` in the Examples/python/import_packages directory, see dd40a25349dadc4011040474334c1fb7be3abecf
- Change import of all of sys - see 81adedd7dd3433d600a584337dcff2335dc12e9b. I'm not entirely happy with this as it adds ```version_info``` into the code and this name might be one that a user is using. How would one reduce the scope of this, other than putting the code into a 'if True: ...' block?

**Comment by mromberg** [comment]
> Change import of all of sys - see 81adedd. I'm not entirely happy with this as it adds version_info into the code and this name might be one that a user is using. How would one reduce the scope of this, other than putting the code into a 'if True: ...' block?

  Yea.  I thought about just pulling in version_into from sys and calling it _swig_version_info  like so:

from sys import version_info as _swig_version_info

  But then it occurred to me that I am not a python historian and I don't know if this 'as' syntax works for all pythons.  If someone else knows if this works for all then that would be better

**Comment by wsfulton** [comment]
I was worried about that too. From what I can see 'import x as y' requires python 2 and later, but given this is a stable branch of SWIG, I don't want to risk anything introducing this. Answering my own question, probably best to pop this code into a helper function instead.

**Comment by m7thon** [comment]
I didn't see this pull request. Sorry. I'll repeat my comment here. You should definitely not add the `version_info` symbol into the module namespace.

> `from sys import version_info as _swig_version_info` is valid for all versions of python 2 [[ref](https://docs.python.org/release/2.0/ref/import.html)]

> You can put the above code snippet for `_swig_absolute_import`, or, if you don't feel like fixing that, then instead `from sys import version_info as _swig_python_version_info` between [these](https://github.com/swig/swig/blob/1495313e53c26f6e0394e0c7f0411fc27f1054ce/Source/Modules/python.cxx#L1050-L1051) lines.

> To put the `del _swig_python_version` or `del _swig_absolute_import` statement at the end of the file, print it [here](https://github.com/swig/swig/blob/1495313e53c26f6e0394e0c7f0411fc27f1054ce/Source/Modules/python.cxx#L1054).

> However, please do **not** use either of `import sys`, or `from sys import version_info`, since it will overwrite any previously defined symbol called "sys" or "version_info" (I can give you a test case that breaks, if you like).

**Comment by m7thon** [comment]
I have a test [future_absolute_import](https://github.com/m7thon/swig/tree/relativeimports-improvements/Examples/python/import_packages/future_absolute_import) added to `import_packages` to show:

* That using `from __future__ import absolute_import` can be tested (and skipped for Python < 2.5). You just need to have `runme.py` import a module that has this first.
* That `-relativeimports` combined with `%pythonbegin %{ from __future__ import absolute_import %}` currently still does not work with Python 2.5 and 2.6 (it is currently fixed by this PR for 2.7).

To be honest, I have no idea why anyone would want to add this to their interface file, but it is explicitely mentioned in the docs under [36.11.3 Enforcing absolute import semantics](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_absimport).

**Comment by wsfulton** [comment]
Of course, don't test the package if python < 2.5! We can use this, thanks.

BTW, don't check in the runme3.py file, it gets generated by ```2to3```.

**Comment by wsfulton** [comment]
```
Testing future_absolute_import - explicit relativeimports for python >= 2.5
Traceback (most recent call last):
  File "runme.py", line 8, in <module>
    import pkg
  File "/home/william/swig/github/swig/Examples/python/import_packages/future_absolute_import/pkg/__init__.py", line 1, in <module>
    from .bar import Pkg_Bar
  File "/home/william/swig/github/swig/Examples/python/import_packages/future_absolute_import/pkg/bar.py", line 108, in <module>
    import foo
ImportError: No module named foo
```
This is for python 2.7. I think you need py2 and py3 packages like the relativeimport1 test to deal with the differences between python 2 and python 3. Can you fix, rebase and create a pull request for this please? Then all the combinations on Travis will be tested.

**Comment by wsfulton** [comment]
We could remove the repeated ```from sys import version_info as _swig_python_version_info``` but I'm running out of time atm. I'd like to make the release candidate this eve, so unless one of you put in a pull request to make further improvements, I think we should go with what we have for 3.0.10.

**Comment by m7thon** [comment]
@wsfulton: Yes, go ahead and release, I currently don't se any serious issues.

I'll keep tinkering towards Option 2 above, i.e., get the default argument conversions working for Python 2 and 3, and maybe fix the imports when `from __future__ import absolute_imports` is used, including making some tests. But I wont rush this.

I see these things are tricky, and the current code is actually quite buggy for corner cases not covered by the tests.

**Pull request merged**
