### PR TITLE
support check typemaps in JS

### LINKED ISSUE #2561: Checking typemaps `%typemap(check)` seem to be absent from JS
There is no `multimap` example in `Examples/javascript` and this does not work - the check is not included at all:

```swig
%module check_typemap

%include exception.i
%include typemaps.i

%inline %{

void circle(double x, double y) {
  double a = x*x + y*y;
  if (a > 1.0) {
    printf("Bad points %g, %g\n", x,y);
  } else {
    printf("Good points %g, %g\n", x,y);
  }
}

%}

%typemap(check) (double cx, double cy) {
   double a = $1*$1 + $2*$2;
   if (a > 1.0) {
	SWIG_exception(SWIG_ValueError,"$1_name and $2_name must be in unit circle");
   }
}
```

Only Ruby has a unit test with a `check` typemap

### PR DESCRIPTION
**Pull request by mmomtchev**
Fixes #2561

### CODE REVIEW

**Comment by mmomtchev** [comment]
@ojwb are all the weird errors due to the fact that I made a `ctest` instead of a `cpptest`? Excluding JSC of course.

**Comment by ojwb** [comment]
> are all the weird errors due to the fact that I made a `ctest` instead of a `cpptest`? Excluding JSC of course.

I don't know what's causing them from looking at the logs, but I don't see why this being a `ctest` would be a problem.

**Comment by ojwb** [comment]
At least one of your problems here is that `SWIG_exception_fail()` isn't a cross-target-language interface (part of #2400).

**Comment by wsfulton** [comment]
It's hard to write tests for typemaps that work for all target languages as typemaps are meant to be target language specific. I suggest this kind of platform neutral trick:
```swig
%{
static bool checked_flag = false;
%}

%typemap(check) (int x, int y) %{
if ($1 == $2 && $1 == 123) {
  checked_flag = true;
}
%}

%catches(const char *) check_the_check_typemap;

%inline %{
void check_the_check_typemap(int x, int y) {
  if (!checked_flag)
    throw "Missing check typemap";
}
%}
```
I suggest using int instead of double as comparisons with double and == is not reliable.

The Javascript runtime test is then simply:
```javascript
typemap_check.check_the_check_typemap(123, 123);
```
If any other values are passed or the check typemap is missing, the thrown C++ exception will be translated into a language specific exception and then fail. The runtime test can be easily copied to all supported languages. I can do that post merge if you like.

**Comment by erezgeva** [comment]
Hi,

I wrote li_constraints_runme for several languages. #2567
I notice that Javascripts, R, scilab do not support the check typemap.
Once you fix the support for Javascripts I can add `li_constraints_runme.js` to test them.

**Comment by erezgeva** [comment]
Hi,

`Lib/constraints.i` already test the check type map.
So I only took @mmomtchev patch for Source/Modules/javascript.cxx.
Add it to #2567 and wrote a new 'Examples/test-suite/javascript/li_constraints_runme.js' to use the already existing test `Examples/test-suite/li_constraints.i`.
The test is very simple and very effective. And do not breaks other languages. 
#2567 pass all checks, very easily.

Once  #2567 is merged, you can close this one.

**Pull request closed without merging**
