### PR TITLE
[OCaml] Fix compilation errors with OCaml 4.09.0

### LINKED ISSUE #1686: error: invalid conversion from ‘const caml_value_t*’ {aka ‘const long int*’} to ‘caml_value_t*’ {aka ‘long int*’}
I got this error (and a few other similar errors) from swig generated code:

----------------------

  CXX      libgv_ocaml_la-gv_ocaml.lo
gv_ocaml.cpp: In function ‘long int caml_long_val_full(caml_value_t, const char*)’:
gv_ocaml.cpp:1362:48: error: invalid conversion from ‘const caml_value_t*’ {aka ‘const long int*’} to ‘caml_value_t*’ {aka ‘long int*’} [-fpermissive]
 1362 |      CAML_VALUE *enum_to_int = caml_named_value(SWIG_MODULE "_enum_to_int");
      |                                ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                const caml_value_t* {aka const long int*}

------------------------   

when building graphviz (www.graphviz.org) on Fedora32 (aka rawhide) using 
      gcc-9.2.1-1.fc32.3.x86_64
      swig-4.0.1-3.fc32.x86_64

I was able to work-around the issue by adding -fpermissive to the CPPFLAGS for this file.

### PR DESCRIPTION
**Pull request by ZackerySpytz**
caml_named_value() was modified to return a const value* in OCaml
4.09.0 (ocaml/ocaml@9f0bebf).

Closes #1686.

### CODE REVIEW

**Comment by wsfulton** [comment]
@ZackerySpytz, looks okay to me, feel free to merge it in. The Travis tests pass, albeit using version 4.02.3.

**Comment by wsfulton** [comment]
Hi @ZackerySpytz, this is meant to be merged into master not the other way round! Much easier to follow what is going on as now there is a pile of irrelevant commits on this pull request. I think I'll just do the merge of your pull request now.

**Comment by ZackerySpytz** [comment]
Hi, William. I hope you are well. I had to fix a merge conflict in `CHANGES.current`. I had done this previously on some of my pull requests without you taking issue, but please forgive me if I'm doing something wrong (I don't believe there is a "preferred" way to handle merge conflicts for the SWIG project?).

**Comment by wsfulton** [comment]
Sorry my fault, I havn't formally written it down anywhere, but merging is done from the pull request branch to master. The github issue should only show the changes that will be merged in, but yours doesn't, sorry I'm not quite sure what you did to cause this. Anyway, what I'm doing now is merging your branch into master using just the first and only commit on the branch.

**Comment by wsfulton** [comment]
Closed in 02862fb278a8d772e1f0480adc935c33b9625da4

**Pull request closed without merging**
