### PR TITLE
fix pep257 warnings

### PR DESCRIPTION
**Pull request by xantares**
minor python docstrings syntax fixes:
- mono-line module docsstring
- rewrite autodoc parameters section in numpydoc style
- on-line summary should end with "."
- adds a blank line after class docstring

### CODE REVIEW

**Comment by wsfulton** [comment]
Did you use a tool to check the style? I think there is a pep257 tool to check this, did you try this out? Is it worth putting this into our testing?

**Comment by xantares** [comment]
Yes, I did use https://github.com/GreenSteam/pep257.
I first integrated it in the make check stage, but then I backed off because I had to disable so much warning types because of the missing docstrings and that it was only useful for the autodoc.i testcase.

**Comment by wsfulton** [comment]
Can you please add to the Python.html documentation this new style that autodoc uses. A comment in the python.cxx about this should also be put in so that future developers know what the style attempted is. A reference to https://github.com/GreenSteam/pep257 would also not go amiss.

**Comment by xantares** [comment]
Ok

**Comment by ojwb** [comment]
@xantares Why did you close this?  It doesn't appear to have been merged yet...

**Comment by xantares** [comment]
it's not clean enough, i'll resubmit

**Pull request closed without merging**
