### PR TITLE
Adjust code for Octave v9

### PR DESCRIPTION
**Pull request by rlaboiss**
In version 9 of Octave, t_id has been replaced by s_t_id.

The proposed changes also work with previous versions of Octave.

### CODE REVIEW

**Comment by wsfulton** [comment]
Which version of Octave fully supported `s_t_id` instead of `t_id`? The merge request may change the minimum version of Octave supported, so may need deferring until the next major release of SWIG.

**Comment by wsfulton** [comment]
We also still need a way to test different versions of Octave since @kwwette unfortunately stopped producing Ubuntu PPAs :(.

**Comment by rlaboiss** [comment]
> Which version of Octave fully supported `s_t_id` instead of `t_id`? 

`t_id` was supported in release 8.4.0
`s_t_id` replaced `t_id` in release 9.0.90

My patch has `#if SWIG_OCTAVE_PREREQ(9,0,0)` instead of `#if SWIG_OCTAVE_PREREQ(9,0,90)`. It will work anyway, because `9.0.90` is the first official release in the `9.x.x` series (it is a release candidate, BTW).

> The merge request may change the minimum version of Octave supported, so may need deferring until the next major release of SWIG.

I think that my pull request will not change the minimum version of Octave supported.

**Comment by rlaboiss** [comment]
> We also still need a way to test different versions of Octave since @kwwette unfortunately stopped producing Ubuntu PPAs :(.

I do not know the details of the CI setting for SWIG, but would it not be possible to use the [Debian Archive](https://www.debian.org/distrib/archive) for that?

**Comment by ojwb** [comment]
Sadly the github CI runs on Ubuntu not Debian.

**Comment by ojwb** [comment]
Looking at the patch, it seems clear it won't affect older Octave version support.

To make up for the lack of much version diversity in CI (it only tests 5.2.0 currently AFAICS), I've kicked off a manual testsuite run with Octave 8.4.0 (I can easily test 9.0.90 and maybe 7.3.0 too).  8.4.0 is still running (gosh it's slow) but this looks like it really ought to be addressed:

```
li_std_string_extra_wrap.cxx:3365:38: warning: ‘octave_value do_binary_op(octave_value::binary_op, const octave_value&, const octave_value&)’ is deprecated: [7]: use 'octave::binary_op' instead [-Wdeprecated-declarations]
 3365 |       octave_value res = do_binary_op(octave_value::op_le,v,w);
      |                          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/octave-8.4.0/octave/../octave/ovl.h:38,
                 from /usr/include/octave-8.4.0/octave/../octave/ov-fcn.h:36,
                 from /usr/include/octave-8.4.0/octave/../octave/ov-builtin.h:35,
                 from /usr/include/octave-8.4.0/octave/../octave/defun-int.h:33,
                 from /usr/include/octave-8.4.0/octave/../octave/defun-dld.h:35,
                 from /usr/include/octave-8.4.0/octave/../octave/oct.h:35,
                 from ./../../../Examples/test-suite/octave/octheaders.hpp:27,
                 from <command-line>:
/usr/include/octave-8.4.0/octave/../octave/ov.h:1773:1: note: declared here
 1773 | do_binary_op (octave_value::binary_op op, const octave_value& a,
      | ^~~~~~~~~~~~
```

This seems to be from this code:

```
Lib/octave/octcontainer.swg:      octave_value res = do_binary_op(octave_value::op_le,v,w);
```

**Comment by ojwb** [comment]
With Octave 9.0.90, SWIG's configure output includes:

```
checking for Octave linker flags... mkoctfile: unknown variable 'RLD_FLAG'
 -L/usr/lib/x86_64-linux-gnu/octave/9.0.90 -rdynamic  -loctinterp -loctave  -lpthread -lm 
```

We could just `2>/dev/null` there, but maybe there's a cleaner solution.

There's more noise about deprecated stuff - lots like this example from `make check-octave-examples`:

```
example_wrap.cxx: In static member function ‘static octave_value octave_swig_type::make_value_hack(const octave_base_value&)’:
example_wrap.cxx:1305:32: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1305 |       ((octave_swig_type &) x).count++;
      |                                ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
```

This seems to be triggered by code in SWIG, e.g.:

```
Lib/octave/octrun.swg:      if (!--count)
```

There are also some actual test failures - it looks like the `do_binary_op` deprecation warnings from 8.4.0 have graduated to build errors as `do_binary_op` doesn't seem to be declared anywhere in the octave 9.0.90 headers:

```
make -C Examples/test-suite/octave li_std_string_extra.cpptest
make: Entering directory '/home/olly/git/swig/Examples/test-suite/octave'
if [ -f ./li_std_string_extra_runme.m ]; then echo "checking octave testcase li_std_string_extra (with run test)" ; else echo "checking octave testcase li_std_string_extra" ; fi
checking octave testcase li_std_string_extra (with run test)
make -f ../../../Examples/Makefile SRCDIR='./' CXXSRCS='' SWIG_LIB_DIR='../../../Lib' SWIGEXE='../../../swig' INCLUDES='-I../../../Examples/test-suite' SWIGOPT='-outcurrentdir -I../../../Examples/test-suite' NOLINK=true TARGET='li_std_string_extra' INTERFACEDIR='../' INTERFACE='li_std_string_extra.i' octave_cpp
make[1]: Entering directory '/home/olly/git/swig/Examples/test-suite/octave'
env SWIG_LIB=../../../Lib  ../../../swig -c++ -octave -DSWIG_OCTAVE_EXTERNAL_OCTHEADERS -outcurrentdir -I../../../Examples/test-suite -o li_std_string_extra_wrap.cxx ./../li_std_string_extra.i
g++ -g -c -I../../../Examples/test-suite/octave -include ../../../Examples/test-suite/octave/octheaders.hpp -fpic -I. -I./ -I/usr/include -std=c++20  li_std_string_extra_wrap.cxx   -I../../../Examples/test-suite   -D_FORTIFY_SOURCE=2 -I/usr/include/octave-9.0.90/octave/.. -I/usr/include/octave-9.0.90/octave -I/usr/include/octave-9.0.90/octave/.. -I/usr/include/octave-9.0.90/octave  -g -Wformat -Werror=format-security -O0
In file included from /usr/include/octave-9.0.90/octave/../octave/ov-base.h:38,
                 from /usr/include/octave-9.0.90/octave/../octave/ov.h:70,
                 from /usr/include/octave-9.0.90/octave/../octave/ovl.h:38,
                 from /usr/include/octave-9.0.90/octave/../octave/ov-fcn.h:36,
                 from /usr/include/octave-9.0.90/octave/../octave/ov-builtin.h:35,
                 from /usr/include/octave-9.0.90/octave/../octave/defun-int.h:33,
                 from /usr/include/octave-9.0.90/octave/../octave/defun-dld.h:35,
                 from /usr/include/octave-9.0.90/octave/../octave/oct.h:35,
                 from ./../../../Examples/test-suite/octave/octheaders.hpp:27,
                 from <command-line>:
/usr/include/octave-9.0.90/octave/../octave/Range.h: In lambda function:
/usr/include/octave-9.0.90/octave/../octave/Range.h:255:22: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
  255 |         idx.loop (n, [=, &array] (octave_idx_type i)
      |                      ^
/usr/include/octave-9.0.90/octave/../octave/Range.h:255:22: note: add explicit ‘this’ or ‘*this’ capture
li_std_string_extra_wrap.cxx: In static member function ‘static octave_value octave_swig_type::make_value_hack(const octave_base_value&)’:
li_std_string_extra_wrap.cxx:1177:32: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1177 |       ((octave_swig_type &) x).count++;
      |                                ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1177:32: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1177 |       ((octave_swig_type &) x).count++;
      |                                ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1177:32: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1177 |       ((octave_swig_type &) x).count++;
      |                                ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx: In destructor ‘virtual octave_swig_type::~octave_swig_type()’:
li_std_string_extra_wrap.cxx:1202:11: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1202 |         ++count;
      |           ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1202:11: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1202 |         ++count;
      |           ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx: In member function ‘octave_value octave_swig_type::as_value()’:
li_std_string_extra_wrap.cxx:1290:9: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1290 |       ++count;
      |         ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1290:9: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1290 |       ++count;
      |         ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx: In member function ‘void octave_swig_type::incref()’:
li_std_string_extra_wrap.cxx:1295:9: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1295 |       ++count;
      |         ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1295:9: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1295 |       ++count;
      |         ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx: In member function ‘void octave_swig_type::decref()’:
li_std_string_extra_wrap.cxx:1299:14: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1299 |       if (!--count)
      |              ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx:1299:14: warning: ‘octave_base_value::count’ is deprecated: [9]: use octave_base_value::m_count instead [-Wdeprecated-declarations]
 1299 |       if (!--count)
      |              ^~~~~
/usr/include/octave-9.0.90/octave/../octave/ov-base.h:938:38: note: declared here
  938 |   octave::refcount<octave_idx_type>& count;
      |                                      ^~~~~
li_std_string_extra_wrap.cxx: In member function ‘bool std::less<octave_value>::operator()(const octave_value&, const octave_value&) const’:
li_std_string_extra_wrap.cxx:3365:26: error: ‘do_binary_op’ was not declared in this scope; did you mean ‘do_sm_binary_op’?
 3365 |       octave_value res = do_binary_op(octave_value::op_le,v,w);
      |                          ^~~~~~~~~~~~
      |                          do_sm_binary_op
make[1]: *** [../../../Examples/Makefile:1084: octave_cpp] Error 1
make[1]: Leaving directory '/home/olly/git/swig/Examples/test-suite/octave'
make: *** [Makefile:46: li_std_string_extra.cpptest] Error 2
make: Leaving directory '/home/olly/git/swig/Examples/test-suite/octave'
```

**Comment by rlaboiss** [comment]
> With Octave 9.0.90 (and also 7.3.0 and 8.4.0, but looking at CI logs not 5.2.0), SWIG's configure output includes:
> 
> ```
> checking for Octave linker flags... mkoctfile: unknown variable 'RLD_FLAG'
>  -L/usr/lib/x86_64-linux-gnu/octave/9.0.90 -rdynamic  -loctinterp -loctave  -lpthread -lm 
> ```
> 
> We could just `2>/dev/null` there, but maybe there's a cleaner solution.

I do not know exactly when the change happened, but the `RLD_FLAG` variable of `mkoctfile` existed in version 3.4.3 and was gone in version 3.6.1.

Yes, `2>/dev/null` would work here. A cleaner way of coping with the problem would be to have a mechanism similar to `SWIG_OCTAVE_PREREQ` in `configure.ac`.

**Comment by rlaboiss** [comment]
> There's more noise about deprecated stuff - lots like this example from `make check-octave-examples`:
>
> [...]

According to Octave's [NEWS.9.md](http://hg.savannah.gnu.org/hgweb/octave/file/dc69e574b97a/etc/NEWS.9.md):

```
    * The member variable `octave_base_value::count` is deprecated and will be
      removed from Octave 11.  Replace all instances with the new name
      `m_count`.
```

I added commit 48f71654727fdf35212f81401bcae1f1c527a24a the the `octave-9` branch, which fixes the issue.

**Comment by rlaboiss** [comment]
> To make up for the lack of much version diversity in CI (it only tests 5.2.0 currently AFAICS), I've kicked off a manual testsuite run with Octave 8.4.0 (I can easily test 9.0.90 and maybe 7.3.0 too). 8.4.0 is still running (gosh it's slow) but this looks like it really ought to be addressed:
> 
> ```
> li_std_string_extra_wrap.cxx:3365:38: warning: ‘octave_value do_binary_op(octave_value::binary_op, const octave_value&, const octave_value&)’ is deprecated: [7]: use 'octave::binary_op' instead [-Wdeprecated-declarations]
>  3365 |       octave_value res = do_binary_op(octave_value::op_le,v,w);
>       |                          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/octave-8.4.0/octave/../octave/ovl.h:38,
>                  from /usr/include/octave-8.4.0/octave/../octave/ov-fcn.h:36,
>                  from /usr/include/octave-8.4.0/octave/../octave/ov-builtin.h:35,
>                  from /usr/include/octave-8.4.0/octave/../octave/defun-int.h:33,
>                  from /usr/include/octave-8.4.0/octave/../octave/defun-dld.h:35,
>                  from /usr/include/octave-8.4.0/octave/../octave/oct.h:35,
>                  from ./../../../Examples/test-suite/octave/octheaders.hpp:27,
>                  from <command-line>:
> /usr/include/octave-8.4.0/octave/../octave/ov.h:1773:1: note: declared here
>  1773 | do_binary_op (octave_value::binary_op op, const octave_value& a,
>       | ^~~~~~~~~~~~
> ```
> 
> This seems to be from this code:
> 
> ```
> Lib/octave/octcontainer.swg:      octave_value res = do_binary_op(octave_value::op_le,v,w);
> ```

`do_binary_op` has been deprecated in Octave 7.  I have added commit 47c6fd5853fe88faea7c5e233a7cd8e2624275e2 to the `octave-9` branch, which fixes the issue.

**Comment by rlaboiss** [comment]
By the way, why there are constructs like this (with `%#` instead of `#`):

```
%#if SWIG_OCTAVE_PREREQ(x,y,z)
[…]
%#endif
```

in some `*.swg` files but not in others?

**Comment by ojwb** [comment]
Thanks for the updates - will rerun the manual tests to double check.

SWIG has a C/C++-like preprocessor (mostly it's a superset), so `#if` and other preprocessor directives get handled by that.  Sometimes you want the compiler to handle a `#if` instead so you want to have it in the generated wrapper file (that's what we want for checking the octave version in use, since that's only known when the wrapper is compiled, not when it's generated).  One way to achieve this is to use `%#if`, etc which get passed through to the generated file with the `%` removed.

However, `%{`...`%}` block contents are copied over verbatim, so `#if` inside such a block should **NOT** get a `%` prefixed (you'll soon find out if you get this wrong as the C/C++ preprocessor will get fed `%#if` and error).

> I do not know exactly when the change happened, but the RLD_FLAG variable of mkoctfile existed in version 3.4.3 and was gone in version 3.6.1.

It doesn't seem quite that simple as Octave 6.4.0 doesn't seem to moan about `RLD_FLAG`:

https://github.com/swig/swig/actions/runs/7896718100/job/21551163253#step:5:172

I think it must have just started giving an empty value somewhere between 3.4.3 and 3.6.1, but only got removed completely in Octave 7 (probably - I saw the error output with 7.3.0).

Using `

**Comment by ojwb** [comment]
For the record, our CI tested this with 5.3.0 and 6.4.0 and I manually ran the examples and testsuite with 7.3.0, 8.4.0 and 9.0.90 - all were clean of warnings[*].  I've updated the Octave chapter of the manual to reflect what we actually test with now as it was very out of date: _"SWIG is regularly tested against the following versions of Octave: 3.8, 4.0, 4.2."_

---

[*] Except I did force use of `-Wno-deprecated` to suppress a warning about lambda implicit this capture being deprecated in C++20 which some code in the Octave headers triggers - I think we only see this because SWIG enables `-std=c++20` for the testsuite so it can test wrapping of C++20 features.  To reproduce run `make -C Examples/octave/callback` in the SWIG tree:

```
In file included from /usr/include/octave-9.0.90/octave/../octave/ov-base.h:38,
                 from /usr/include/octave-9.0.90/octave/../octave/ov.h:70,
                 from /usr/include/octave-9.0.90/octave/../octave/ovl.h:38,
                 from /usr/include/octave-9.0.90/octave/../octave/ov-fcn.h:36,
                 from /usr/include/octave-9.0.90/octave/../octave/ov-builtin.h:35,
                 from /usr/include/octave-9.0.90/octave/../octave/defun-int.h:33,
                 from /usr/include/octave-9.0.90/octave/../octave/defun-dld.h:35,
                 from /usr/include/octave-9.0.90/octave/../octave/oct.h:35,
                 from example_wrap.cxx:199:
/usr/include/octave-9.0.90/octave/../octave/Range.h: In lambda function:
/usr/include/octave-9.0.90/octave/../octave/Range.h:255:22: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
  255 |         idx.loop (n, [=, &array] (octave_idx_type i)
      |                      ^
/usr/include/octave-9.0.90/octave/../octave/Range.h:255:22: note: add explicit ‘this’ or ‘*this’ capture
```

Note that we get this even with Octave 9.0.90 so it would be useful if someone who actually uses Octave could report this warning to the Octave developers as it would be better resolved before compilers start defaulting to C++20.

**Comment by rlaboiss** [comment]
> Note that we get this even with Octave 9.0.90 so it would be useful if someone who actually uses Octave could report this warning to the Octave developers as it would be better resolved before compilers start defaulting to C++20.

It is [done](https://savannah.gnu.org/bugs/index.php?65318).

**Comment by rlaboiss** [comment]
> > Note that we get this even with Octave 9.0.90 so it would be useful if someone who actually uses Octave could report this warning to the Octave developers as it would be better resolved before compilers start defaulting to C++20.
> 
> It is [done](https://savannah.gnu.org/bugs/index.php?65318).

A fix for the issue [has been committed](https://savannah.gnu.org/bugs/?65318#comment12) by the Octave upstream authors.

**Comment by kwwette** [comment]
> We also still need a way to test different versions of Octave since @kwwette unfortunately stopped producing Ubuntu PPAs :(.

I'm not sure if the SWIG CI builds can use Docker images - if so, there have images here going back to v4.0: https://hub.docker.com/r/gnuoctave/octave/tags

**Comment by ojwb** [comment]
> I'm not sure if the SWIG CI builds can use Docker images - if so, there have images here going back to v4.0: https://hub.docker.com/r/gnuoctave/octave/tags

Github actions support running in a docker image:

https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

That doesn't say if/how you can specify this optionally so it could work within SWIG's single big build matrix, but I guessed an empty value might mean that and it does seem to, so we could use

```
    runs-on: ${{ matrix.os || 'ubuntu-20.04' }}
    container: ${{ matrix.container }}
```

and then have entries such as this (we could probably select `ubuntu-latest` automatically if `container` is set):

```
        - SWIGLANG: octave
          os: ubuntu-latest
          container: gnuoctave/octave:9.1.0
```

However I pushed a quick branch to test this and the container octave builds all fail, either with:

```
+ /usr/bin/sudo apt-get install -y ccache
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package ccache
  Error: Restoring cache failed: Error: The process '/usr/bin/sh' failed with exit code 100
```

Or with:

```
/usr/bin/docker exec  92539773d03321101801ec14cd992825a36d47f945e0383f5c22891566fb23d0 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

(The reported GLIBC symbol version(s) seem to vary between the docker images that fail this way.)

I think this needs someone with more interest and time they're willing to invest in fiddling with setting up Octave CI builds than I have.

**Pull request merged**
