### PR TITLE
Add shared pointer support in javascript

### PR DESCRIPTION
**Pull request by diorcety**
All is said

### CODE REVIEW

**Comment by wsfulton** [comment]
@oliver---- I'd like to merge this in, is this okay with you?

**Comment by ojwb** [comment]
@oliver---- Did you miss William's question above?  (I notice it was asked on xmas eve!)

**Comment by patnolan33** [comment]
@oliver---- or @wsfulton Are there plans to merge this soon? I could really use the std::shared_ptr support for javascript right now, and I'm wondering if I should wait for a merge or just duplicate the changes in this branch on my end.

**Comment by wsfulton** [comment]
As there is no input from Javascript maintainers, I'll accept the patch if runtime tests are added to show the patch is good. If someone updates the patch to remove the conflicts and these 4 Java tests are converted to Javascript and added:

Examples/test-suite/java/li_boost_shared_ptr_attribute_runme.java
Examples/test-suite/java/li_boost_shared_ptr_bits_runme.java
Examples/test-suite/java/li_boost_shared_ptr_runme.java
Examples/test-suite/java/li_boost_shared_ptr_template_runme.java

Shouldn't be hard for someone with Javascript background and it will be a great addition to SWIG.

**Comment by fattredd** [comment]
Any reason this hasn't been merged yet?

**Comment by wsfulton** [comment]
Superceded by #1365

**Pull request closed without merging**
