### PR TITLE
"ignore" warning (2)

### PR DESCRIPTION
**Pull request by wkalinin**
refactoring: 2 ways of ignoring symbol in add_symbols() merged for clarity

### CODE REVIEW

**Comment by vadz** [comment]
FWIW I agree that this improves the code clarity, thanks.

**Comment by wsfulton** [comment]
@wkalinin could you please check why since this commit, Perl has many numerous warnings in the test-suite such as:
```
checking perl5 testcase apply_signed_char (with run test)
../../../../../Examples/test-suite/perl5/../apply_signed_char.i:39: Warning 362: operator= ignored
```

**Comment by wkalinin** [comment]
I'll look at it.

**Comment by wkalinin** [comment]
Indeed, I didn't quite correctly merged these 2 conditional branches, and private symbols start generating warnings. Fixed now (waiting for travis results )

**Comment by wkalinin** [comment]
That turned out to be rather tricky. I added some comments to help understanding this piece of code next time.

**Comment by wkalinin** [comment]
I think it's ok to merge now: https://github.com/swig/swig/pull/476

**Pull request merged**
