### PR TITLE
Add recently added nested_in_template to the list of test cases

### PR DESCRIPTION
**Pull request by vadz**
This should have been part of 30bb977a6436fa7903aca041606c1110d37a2401

See #1358.

### CODE REVIEW

**Comment by wsfulton** [comment]
There are a few problems showing in the Appveyor and Travis tests for this

**Comment by vadz** [comment]
I forgot to update Python part of the test after changing double to int, sorry... Fixed now.

**Comment by vadz** [comment]
Appveyor still fails, but for seemingly unrelated reasons ("Fatal Python error: failed to get random numbers to initialize Python" in Python 3 builds, which pass under Travis).

**Comment by vadz** [comment]
This warning was there since a long time but didn't appear in the tests. It's fixed by #1359.

**Pull request merged**
