### PR TITLE
Complain if any new shift/reduce conflicts are introduced in the grammar.

### PR DESCRIPTION
**Pull request by vadz**
Currently there are 6 of them, suppress warning about them but do complain if
any new ones are introduced.

----

This basically formalizes what you wrote in a comment to PR #170.

### CODE REVIEW

**Comment by vadz** [comment]
P.S. Tested with 2.3 (under OS X 10.8) too, works as well.

**Comment by vadz** [comment]
I've tested this with 3.0, works just fine too. IMO the comment is overcautious (d357bec8 doesn't even say that any such version of Bison was actually observed) and the benefits outweigh the risks.

**Comment by vadz** [comment]
The crash in C# test is worrisome but I don't think it can be related to the change in this PR.

**Comment by vadz** [comment]
Can this trivial change be merged?

**Comment by ojwb** [comment]
It seems good to me.  Without this enabled, it's not clear to people that the existing SR conflicts are OK, but that a patch introducing new ones needs needs careful inspection.

The only evidence of bugs with `%expect` in bison seems to be a rather vague allusion in the documentation of byacc, which is a rival project to bison, so not an impartial source of information.  There's no version or time indicated for these alleged issues - even if correct when written, the information could be decades out of date.  The only way to really find out if there are any compatibility issues which are relevant is to enable this and try it.

Source distributions include the bison-generated files, so any problems won't affect end users building SWIG, only those working on SWIG.

**Comment by vadz** [comment]
I am taking [this comment](https://github.com/swig/swig/commit/d357bec829d08ee96afe8ca8bf6d8631f6b983c9#commitcomment-17154766) as an approval and will commit this soon.

**Pull request closed without merging**
