### PR TITLE
Attempt to fix isfinite() checks to work with all C++11 compilers

### PR DESCRIPTION
**Pull request by ojwb**
Fixes https://github.com/swig/swig/issues/615 and
https://github.com/swig/swig/pull/788

### CODE REVIEW

**Comment by wsfulton** [comment]
i like it,  very neat solution. There is one potential problem I can see though. If the std namespace is not defined (which it may not be with just the math.h header include),  then the `using namespace std;` will give a compiler error. This can be solved by adding in `namespace std {}` into the fragment, but I suspect that SWIG unfortunately, includes enough STL headers that std is defined somewhere, so may not be a problem in practice, even with with a minimal example.

Also, I think you should add SWIGRUNTIME to SWIG_isfinite_func to avoid linking problems when using multiple modules and %import.

**Comment by ojwb** [comment]
Good point about `namespace std { }`.  For the second point, might be better to just make it inline, since it's just a forwarding wrapper so definitely wants to be inlined.  Will address later this weekend (or feel free to push a commit to the branch).

**Comment by ojwb** [comment]
> If the std namespace is not defined (which it may not be with just the `math.h` header include), then the `using namespace std;` will give a compiler error.

FWIW, this does not actually seem to result in a compiler error (tested with GCC and clang), though clang gives a warning which we want to avoid:

```
$ echo 'using namespace std;'|clang++-4.0 -Wall -W -x c++ -c -o /dev/null -
<stdin>:1:17: warning: using directive refers to implicitly-defined namespace
      'std'
using namespace std;
                ^
1 warning generated.
```

**Comment by wsfulton** [comment]
Let's go with this then. Indentation is conventionally 2 not 4 spaces though.

**Pull request merged**
