### PR TITLE
Python: Unify string quoting

### PR DESCRIPTION
**Pull request by cher-nov**
**Before:**

BEFORE

**After:**

AFTER

This is a pretty common notation in Python 3: https://stackoverflow.com/a/56190

Actually it could be nice to use this notation everywhere in Python generator, so if the SWIG maintainers agree, I would expand my PR with it, or make an additional one.

### CODE REVIEW

**Comment by vadz** [comment]
I'm not really sure if this has any real benefit (the convention described in the linked SO answer seems reasonable, but I don't think it's universal), but OTOH I don't see any reason to not apply this neither.

If we do want to standardize on using single quotes in SWIG-generated code, we probably should have a comment somewhere in `Python.cxx` explaining this.

**Comment by cher-nov** [comment]
> I'm not really sure if this has any real benefit (the convention described in the linked SO answer seems reasonable, but I don't think it's universal), but OTOH I don't see any reason to not apply this neither.

This is where syntax highlighting stumbles.

**Comment by vadz** [comment]
> This is where syntax highlighting stumbles.

Strange, why should syntax highlighting have problems with double-quoted strings? Or, at least, more problems than with single-quoted ones?

**Comment by cher-nov** [comment]
> Strange, why should syntax highlighting have problems with double-quoted strings? Or, at least, more problems than with single-quoted ones?

This is not an error, it just highligth it with the same color as natural language strings when we use different colors for double-quoted and single-quoted strings, according to the aforementioned notation. :)

**Comment by wsfulton** [comment]
I took a look at a few files and it looks like SWIG mostly generates double quotes. Also after running the test-suite, I get:
```
$ grep '"' Examples/test-suite/python/*.py | wc -l
8516
$ grep "'" Examples/test-suite/python/*.py | wc -l
3782
```
Quotes on one line ought to be the same style, so happy to have a patch that fixes that. PEP8 says
> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it. 

My vote is for double quotes given that seems to be mostly what is used already and I unapologetically prefer it given it is what C/C++ programmers use and whom SWIG is targetting and we need a reason to choose one over the other that isn't going to start a flame war.

I suggest using a linter to check the patch is good. Maybe https://github.com/zheller/flake8-quotes.

**Comment by cher-nov** [comment]
> My vote is for double quotes given that seems to be mostly what is used already and I unapologetically prefer it given it is what C/C++ programmers use and whom SWIG is targetting and we need a reason to choose one over the other that isn't going to start a flame war.

Maybe add an option for the Python generator? Run-time or at least compile-time.

**Comment by wsfulton** [comment]
We have option bloat in SWIG which is causing various maintenance headaches and we recently been trying to cut down number of options. Adding this as an option doesn't really add any value, so I say let's have just one quote style.

**Comment by cher-nov** [comment]
@wsfulton I've updated the PR, please review.

**Comment by wsfulton** [comment]
Looks good, I'll merge this in. Did you use any linters to check the output? Would be nice to also have a linter tool to check we keep consistent quotes in our CI builds.

**Pull request merged**
