### PR TITLE
Require py>=3.3

### PR DESCRIPTION
**Pull request by jschueller**
see #2314

### CODE REVIEW

**Comment by ojwb** [comment]
#2314 says "drop support for Python 3.2" not "drop support for Python <= 3.2" - I very much doubt @wsfulton is suggesting we also drop Python 2 support as you're attempting to do here.

**Comment by jschueller** [comment]
oh, I thoughts his arguments applied to 2.7 too
I guess there's not much to do then

**Comment by wsfulton** [comment]
Yeah, sorry if not entirely clear, but it is to drop just 3.2 support.

**Comment by jschueller** [comment]
ok

**Pull request closed without merging**
