### PR TITLE
D: Replace deprecated imports (package std.c)

### LINKED ISSUE #1593: D: Replace broken imports in generated source code
With newer versions of dmd (I'm using v2.086.1) the generated source code is not compilable anymore due to broken imports. The following two imports must be replaced:

- `static import std.c.string;` -> `static import core.stdc.string;`
- `import std.c.linux.linux;` -> `import core.sys.posix.dlfcn;`

### PR DESCRIPTION
**Pull request by msteinbeck**
This PR fixes #1593. Tested with DMD (v2.086.1), GDC (8.2.0), and LDC (1.16.0).

### CODE REVIEW

**Comment by wsfulton** [comment]
What minimum versions of the compilers does this now require? @msteinbeck, did you run the entire test-suite and examples?

@dnadlinger, okay with you? Also we are only testing DMD 2.066.0. Should we also be testing GDC and LDC on Travis? There is no mention of these various compilers in the D docs.

**Comment by msteinbeck** [comment]
According the DMD's [changelog](https://dlang.org/changelog/2.081.0.html#remove_std_c) `std.c` was removed with 2.081.0. I don't know when GDC and LDC removed this package though.

> @msteinbeck, did you run the entire test-suite and examples?

I assumed that your CI already runs the entire test suite.

**Comment by wsfulton** [comment]
Hi @msteinbeck. Our regression testing runs all the examples and the test-suite on Travis. You can get to the results of the CI testing of this patch by clicking on "Show all checks" in the green box towards the end of this page.

As we test with 2.066.0 and not 2.081.0, I would like to know what you tested, hence asking

>  did you run the entire test-suite and examples?

Also I asked what the minimum compilers are now once the patch has been applied. You mentioned the maximum compiler version that will work prior to your change, which an answer to a different question! ;) Changing the minimum compiler required is an important piece of information for users which I'd like to see documented.

If D is expected to work with different compilers (GDC/LCD), I'd like to see our testing include that, but needs someone to give details on how to install these compilers and to check that the examples and test-suite does actually work with them.

**Comment by wsfulton** [comment]
I added testing of 2.081.0 on Travis and the failures this pull request is addressing can be seen on a recent build such as https://travis-ci.org/swig/swig/jobs/636530936. Error is
```
Error: module `string` is in file 'std/c/string.d' which cannot be read
```
@msteinbeck can you please push an update to the pull request to trigger new testing? As a suggestion you could update the D.html docs with something relevant to the change and push that to trigger the new build. I had various errors which may or may not be related, but it would be good to see them on Travis and see if you know what it is about.

**Comment by msteinbeck** [comment]
Thank you @wsfulton. I totally forgot about this PR due to my other obligations. I'll update the D.html file as you suggested.

**Comment by msteinbeck** [comment]
Well, I merged the current master into this PR, introducing quite some file changes. If desired, I'll open another PR. At least this triggers a new build.

**Comment by wsfulton** [comment]
Mmm, I can't see the wood for the trees now in this pull request. However, the Travis D testing shows more issues with this version of D, see https://travis-ci.org/swig/swig/jobs/636780153?utm_medium=notification&utm_source=github_status. I'm not sure if they are related to your pull request, I guess not as many more tests pass than before. Can you confirm? If you are able to help with these problems too, that would be much appreciated (in separate pull requests).

**Comment by wsfulton** [comment]
ping @msteinbeck msteinbeck, did you make any progress on fixing this pull request?

**Comment by msteinbeck** [comment]
I'll create a new PR based on the current HEAD later this day.

**Comment by msteinbeck** [comment]
See  #1709

**Pull request closed without merging**
